/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core.ops

import info.mx.core_generated.ops.AbstractMxInfoServiceConfiguration

class MxInfoServiceConfiguration : AbstractMxInfoServiceConfiguration()
