/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core.ops

import android.content.Intent
import android.os.Build
import info.mx.core_generated.ops.AbstractMxInfoService
import timber.log.Timber

class MxInfoService : AbstractMxInfoService(false) {

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            try {
                return super.onStartCommand(intent, flags, startId)
            } catch (e: android.app.ForegroundServiceStartNotAllowedException) {
                Timber.w("MxInfoService cannot start foreground from background, stopping")
                stopSelf()
                return START_NOT_STICKY
            }
        }
        return super.onStartCommand(intent, flags, startId)
    }
}
