/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core.ops

import info.mx.core_generated.ops.AbstractMxInfoServiceOperationConfigurationRegistry

class MxInfoServiceOperationConfigurationRegistry :
    AbstractMxInfoServiceOperationConfigurationRegistry()
