/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops

import com.robotoworks.mechanoid.ops.OperationService

class MxInfoProcessor(service: OperationService?) : AbstractMxInfoProcessor(service, false)
