/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops;

import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

public abstract class AbstractStageingService extends OperationService {
	
	public static final OperationServiceConfiguration CONFIG = new StageingServiceConfiguration();
	
	@Override
	protected OperationProcessor createProcessor() {
		return new StageingProcessor(this);
	}
	
	public AbstractStageingService(boolean enableLogging) {
		super(enableLogging);
	}
}
