/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import android.content.Intent;
import android.os.Bundle;

public abstract class AbstractOpDownLoadImageOperation extends Operation {
	public static final String ACTION_OP_DOWN_LOAD_IMAGE = "info.mx.tracks.ops.MxInfoService.actions.OP_DOWN_LOAD_IMAGE";

	public static final String EXTRA_PICTURE_ID = "info.mx.tracks.ops.MxInfoService.extras.PICTURE_ID";
	public static final String EXTRA_SIZE = "info.mx.tracks.ops.MxInfoService.extras.SIZE";
	public static final String EXTRA_THUMB = "info.mx.tracks.ops.MxInfoService.extras.THUMB";

	static class Args {
		public long pictureId;
		public int size;
		public boolean thumb;
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpDownLoadImageOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractOpDownLoadImageOperation.ACTION_OP_DOWN_LOAD_IMAGE, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent(long pictureId, int size, boolean thumb) {
		Intent intent = new Intent(ACTION_OP_DOWN_LOAD_IMAGE);
		intent.setClass(Mechanoid.getApplicationContext(), MxInfoService.class);
		
		Bundle extras = new Bundle();
		extras.putLong(EXTRA_PICTURE_ID, pictureId);
		extras.putInt(EXTRA_SIZE, size);
		extras.putBoolean(EXTRA_THUMB, thumb);
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		Bundle extras = context.getIntent().getExtras();
		args.pictureId = extras.getLong(EXTRA_PICTURE_ID);
		args.size = extras.getInt(EXTRA_SIZE);
		args.thumb = extras.getBoolean(EXTRA_THUMB);
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
