/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import android.content.Intent;
import android.os.Bundle;

public abstract class AbstractOpGetWeatherCachedOperation extends Operation {
	public static final String ACTION_OP_GET_WEATHER_CACHED = "info.mx.tracks.ops.MxInfoService.actions.OP_GET_WEATHER_CACHED";

	public static final String EXTRA_TRACK_CLIENT_ID = "info.mx.tracks.ops.MxInfoService.extras.TRACK_CLIENT_ID";

	static class Args {
		public long trackClientId;
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpWeatherCachedOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			android.os.Bundle matcher = new android.os.Bundle();
			android.os.Bundle intentExtras = intent.getExtras();
			matcher.putLong(
				OpWeatherCachedOperation.EXTRA_TRACK_CLIENT_ID,
				intentExtras.getLong(OpWeatherCachedOperation.EXTRA_TRACK_CLIENT_ID));
			
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractOpGetWeatherCachedOperation.ACTION_OP_GET_WEATHER_CACHED, matcher);

			return existingRequest;
		}
	}
	
	public static final Intent newIntent(long trackClientId) {
		Intent intent = new Intent(ACTION_OP_GET_WEATHER_CACHED);
		intent.setClass(Mechanoid.getApplicationContext(), MxInfoService.class);
		
		Bundle extras = new Bundle();
		extras.putLong(EXTRA_TRACK_CLIENT_ID, trackClientId);
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		Bundle extras = context.getIntent().getExtras();
		args.trackClientId = extras.getLong(EXTRA_TRACK_CLIENT_ID);
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
