/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops;

import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationProcessor;			

public abstract class AbstractMxInfoProcessor extends OperationProcessor {

	@Override
	protected Operation createOperation(String action) {
		return MxInfoService.CONFIG
			.getOperationConfigurationRegistry()
			.getOperationConfiguration(action)
			.createOperation();
	}
	
	public AbstractMxInfoProcessor(OperationService service, boolean enableLogging) {
		super(service, enableLogging);
	}
}
