/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxInfoDBMigrationV6 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"alter table tracks add column lastAsked integer default 0 "
		);	
		db.execSQL(
			"create index I_tracks_id on tracks (_id) "
		);	
		db.execSQL(
			"create index I_pictures_tracks_id on pictures (track_restId) "
		);	
		db.execSQL(
			"create index I_events_tracks_id on events (track_restId) "
		);	
		db.execSQL(
			"create index I_ratings_tracks_id on ratings (track_restId) "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
