/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;
import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxInfoDBMigrationV2 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"alter table trackstage add column androidid text "
		);	
		db.execSQL(
			"alter table trackstage add column approved integer "
		);	
		db.execSQL(
			"alter table trackstage add column track_restId integer "
		);	
		db.execSQL(
			"create view userActivity as " +
			"select _id as _id, androidid as androidid, approved as approved, count(*) as cnt from trackstage " +
			"group by androidid, approved "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
