/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core.ops.google

import info.mx.core_generated.ops.google.AbstractMxGoogleServiceOperationConfigurationRegistry

class MxGoogleServiceOperationConfigurationRegistry :
    AbstractMxGoogleServiceOperationConfigurationRegistry()
