/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.ops;

import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

import info.mx.core.ops.MxInfoProcessor;
import info.mx.core.ops.MxInfoServiceConfiguration;

public abstract class AbstractMxInfoService extends OperationService {
	
	public static final OperationServiceConfiguration CONFIG = new MxInfoServiceConfiguration();
	
	@Override
	protected OperationProcessor createProcessor() {
		return new MxInfoProcessor(this);
	}
	
	public AbstractMxInfoService(boolean enableLogging) {
		super(enableLogging);
	}
}
