/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops.google

import com.robotoworks.mechanoid.ops.OperationService

class MxGoogleProcessor(service: OperationService?) : AbstractMxGoogleProcessor(service, false)
