/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.ops.google;

import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

import info.mx.core.ops.google.MxGoogleProcessor;
import info.mx.core.ops.google.MxGoogleServiceConfiguration;

public abstract class AbstractMxGoogleService extends OperationService {
	
	public static final OperationServiceConfiguration CONFIG = new MxGoogleServiceConfiguration();
	
	@Override
	protected OperationProcessor createProcessor() {
		return new MxGoogleProcessor(this);
	}
	
	public AbstractMxGoogleService(boolean enableLogging) {
		super(enableLogging);
	}
}
