/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.tracks.sqlite.MxInfoDBContract.Country;
import info.mx.tracks.sqlite.MxInfoDBContract.Country.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class CountryRecord extends ActiveRecord implements Parcelable {

	private static final ActiveRecordFactory<CountryRecord> sFactory = new ActiveRecordFactory<>() {
        @Override
        public CountryRecord create(Cursor c) {
            return fromCursor(c);
        }

        @Override
        public String[] getProjection() {
            return PROJECTION;
        }

        @Override
        public Uri getContentUri() {
            return Country.CONTENT_URI;
        }
    };

    			public static ActiveRecordFactory<CountryRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<CountryRecord> CREATOR 
    	= new Parcelable.Creator<>() {
        public CountryRecord createFromParcel(Parcel in) {
            return new CountryRecord(in);
        }

        public CountryRecord[] newArray(int size) {
            return new CountryRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Country._ID,
    	Country.COUNTRY,
    	Country.SHOW
    };
    
    public interface Indices {
    	int _ID = 0;
    	int COUNTRY = 1;
    	int SHOW = 2;
    }
    
    private String mCountry;
    private boolean mCountryDirty;
    private long mShow;
    private boolean mShowDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setCountry(String country) {
    	mCountry = country;
    	mCountryDirty = true;
    }
    
    public String getCountry() {
    	return mCountry;
    }
    
    public void setShow(long show) {
    	mShow = show;
    	mShowDirty = true;
    }
    
    public long getShow() {
    	return mShow;
    }
    
    
    public CountryRecord() {
    	super(Country.CONTENT_URI);
	}
	
	private CountryRecord(Parcel in) {
    	super(Country.CONTENT_URI);
    	
		setId(in.readLong());
		
		mCountry = in.readString();
		mShow = in.readLong();
		
		boolean[] dirtyFlags = new boolean[2];
		in.readBooleanArray(dirtyFlags);
		mCountryDirty = dirtyFlags[0];
		mShowDirty = dirtyFlags[1];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeString(mCountry);
		dest.writeLong(mShow);
		dest.writeBooleanArray(new boolean[] {
			mCountryDirty,
			mShowDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Country.newBuilder();

		if(mCountryDirty) {
			builder.setCountry(mCountry);
		}
		if(mShowDirty) {
			builder.setShow(mShow);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mCountryDirty = dirty;
		mShowDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setCountry(c.getString(Indices.COUNTRY));
		setShow(c.getLong(Indices.SHOW));
	}
	
	public static CountryRecord fromCursor(Cursor c) {
	    CountryRecord item = new CountryRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}

    @SuppressWarnings("deprecation")
	public static CountryRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(CountryRecord.class.getClassLoader());
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
			return bundle.getParcelable(key, CountryRecord.class);
		} else {
			return bundle.getParcelable(key);
		}
	}
	
	public static CountryRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Country.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
