/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.tracks.sqlite.MxInfoDBContract.Favorits;
import info.mx.tracks.sqlite.MxInfoDBContract.Favorits.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class FavoritsRecord extends ActiveRecord implements Parcelable {

	private static ActiveRecordFactory<FavoritsRecord> sFactory = new ActiveRecordFactory<FavoritsRecord>() {
		@Override
		public FavoritsRecord create(Cursor c) {
			return fromCursor(c);
		}
		
		@Override
		public String[] getProjection() {
			return PROJECTION;
		}

        @Override
                    public Uri getContentUri() {
                        return Favorits.CONTENT_URI;
                    }
                };

    			public static ActiveRecordFactory<FavoritsRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<FavoritsRecord> CREATOR 
    	= new Parcelable.Creator<FavoritsRecord>() {
        public FavoritsRecord createFromParcel(Parcel in) {
            return new FavoritsRecord(in);
        }

        public FavoritsRecord[] newArray(int size) {
            return new FavoritsRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Favorits._ID,
    	Favorits.TRACK_REST_ID
    };
    
    public interface Indices {
    	int _ID = 0;
    	int TRACK_REST_ID = 1;
    }
    
    private long mTrackRestId;
    private boolean mTrackRestIdDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setTrackRestId(long trackRestId) {
    	mTrackRestId = trackRestId;
    	mTrackRestIdDirty = true;
    }
    
    public long getTrackRestId() {
    	return mTrackRestId;
    }
    
    
    public FavoritsRecord() {
    	super(Favorits.CONTENT_URI);
	}
	
	private FavoritsRecord(Parcel in) {
    	super(Favorits.CONTENT_URI);
    	
		setId(in.readLong());
		
		mTrackRestId = in.readLong();
		
		boolean[] dirtyFlags = new boolean[1];
		in.readBooleanArray(dirtyFlags);
		mTrackRestIdDirty = dirtyFlags[0];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mTrackRestId);
		dest.writeBooleanArray(new boolean[] {
			mTrackRestIdDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Favorits.newBuilder();

		if(mTrackRestIdDirty) {
			builder.setTrackRestId(mTrackRestId);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mTrackRestIdDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setTrackRestId(c.getLong(Indices.TRACK_REST_ID));
	}
	
	public static FavoritsRecord fromCursor(Cursor c) {
	    FavoritsRecord item = new FavoritsRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}
	
	public static FavoritsRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(FavoritsRecord.class.getClassLoader());
		return bundle.getParcelable(key);
	}
	
	public static FavoritsRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Favorits.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
