/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.tracks.sqlite.MxInfoDBContract.Picturesum;
import info.mx.tracks.sqlite.MxInfoDBContract.Picturesum.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class PicturesumRecord extends ActiveRecord implements Parcelable {

	private static final ActiveRecordFactory<PicturesumRecord> sFactory = new ActiveRecordFactory<>() {
        @Override
        public PicturesumRecord create(Cursor c) {
            return fromCursor(c);
        }

        @Override
        public String[] getProjection() {
            return PROJECTION;
        }

        @Override
        public Uri getContentUri() {
            return Picturesum.CONTENT_URI;
        }
    };

    			public static ActiveRecordFactory<PicturesumRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<PicturesumRecord> CREATOR 
    	= new Parcelable.Creator<>() {
        public PicturesumRecord createFromParcel(Parcel in) {
            return new PicturesumRecord(in);
        }

        public PicturesumRecord[] newArray(int size) {
            return new PicturesumRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Picturesum._ID,
    	Picturesum.TRACK_REST_ID,
    	Picturesum.PICTURECOUNT
    };
    
    public interface Indices {
    	int _ID = 0;
    	int TRACK_REST_ID = 1;
    	int PICTURECOUNT = 2;
    }
    
    private long mTrackRestId;
    private boolean mTrackRestIdDirty;
    private long mPicturecount;
    private boolean mPicturecountDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setTrackRestId(long trackRestId) {
    	mTrackRestId = trackRestId;
    	mTrackRestIdDirty = true;
    }
    
    public long getTrackRestId() {
    	return mTrackRestId;
    }
    public void setPicturecount(long picturecount) {
    	mPicturecount = picturecount;
    	mPicturecountDirty = true;
    }
    
    public long getPicturecount() {
    	return mPicturecount;
    }
    
    public PicturesumRecord() {
    	super(Picturesum.CONTENT_URI);
	}
	
	private PicturesumRecord(Parcel in) {
    	super(Picturesum.CONTENT_URI);
    	
		setId(in.readLong());
		
		mTrackRestId = in.readLong();
		mPicturecount = in.readLong();
		
		boolean[] dirtyFlags = new boolean[2];
		in.readBooleanArray(dirtyFlags);
		mTrackRestIdDirty = dirtyFlags[0];
		mPicturecountDirty = dirtyFlags[1];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mTrackRestId);
		dest.writeLong(mPicturecount);
		dest.writeBooleanArray(new boolean[] {
			mTrackRestIdDirty,
			mPicturecountDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Picturesum.newBuilder();

		if(mTrackRestIdDirty) {
			builder.setTrackRestId(mTrackRestId);
		}
		if(mPicturecountDirty) {
			builder.setPicturecount(mPicturecount);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mTrackRestIdDirty = dirty;
		mPicturecountDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setTrackRestId(c.getLong(Indices.TRACK_REST_ID));
		setPicturecount(c.getLong(Indices.PICTURECOUNT));
	}
	
	public static PicturesumRecord fromCursor(Cursor c) {
	    PicturesumRecord item = new PicturesumRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}

    @SuppressWarnings("deprecation")
	public static PicturesumRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(PicturesumRecord.class.getClassLoader());
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
			return bundle.getParcelable(key, PicturesumRecord.class);
		} else {
			return bundle.getParcelable(key);
		}
	}
	
	public static PicturesumRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Picturesum.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
