/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.tracks.sqlite.MxInfoDBContract.Route;
import info.mx.tracks.sqlite.MxInfoDBContract.Route.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class RouteRecord extends ActiveRecord implements Parcelable {

	private static final ActiveRecordFactory<RouteRecord> sFactory = new ActiveRecordFactory<>() {
        @Override
        public RouteRecord create(Cursor c) {
            return fromCursor(c);
        }

        @Override
        public String[] getProjection() {
            return PROJECTION;
        }

        @Override
        public Uri getContentUri() {
            return Route.CONTENT_URI;
        }
    };

    			public static ActiveRecordFactory<RouteRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<RouteRecord> CREATOR 
    	= new Parcelable.Creator<>() {
        public RouteRecord createFromParcel(Parcel in) {
            return new RouteRecord(in);
        }

        public RouteRecord[] newArray(int size) {
            return new RouteRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Route._ID,
    	Route.TRACK_CLIENT_ID,
    	Route.LONGITUDE,
    	Route.LATITUDE,
    	Route.CONTENT,
    	Route.CREATED
    };
    
    public interface Indices {
    	int _ID = 0;
    	int TRACK_CLIENT_ID = 1;
    	int LONGITUDE = 2;
    	int LATITUDE = 3;
    	int CONTENT = 4;
    	int CREATED = 5;
    }
    
    private long mTrackClientId;
    private boolean mTrackClientIdDirty;
    private double mLongitude;
    private boolean mLongitudeDirty;
    private double mLatitude;
    private boolean mLatitudeDirty;
    private String mContent;
    private boolean mContentDirty;
    private long mCreated;
    private boolean mCreatedDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setTrackClientId(long trackClientId) {
    	mTrackClientId = trackClientId;
    	mTrackClientIdDirty = true;
    }
    
    public long getTrackClientId() {
    	return mTrackClientId;
    }
    
    public void setLongitude(double longitude) {
    	mLongitude = longitude;
    	mLongitudeDirty = true;
    }
    
    public double getLongitude() {
    	return mLongitude;
    }
    
    public void setLatitude(double latitude) {
    	mLatitude = latitude;
    	mLatitudeDirty = true;
    }
    
    public double getLatitude() {
    	return mLatitude;
    }
    
    public void setContent(String content) {
    	mContent = content;
    	mContentDirty = true;
    }
    
    public String getContent() {
    	return mContent;
    }
    
    public void setCreated(long created) {
    	mCreated = created;
    	mCreatedDirty = true;
    }
    
    public long getCreated() {
    	return mCreated;
    }
    
    
    public RouteRecord() {
    	super(Route.CONTENT_URI);
	}
	
	private RouteRecord(Parcel in) {
    	super(Route.CONTENT_URI);
    	
		setId(in.readLong());
		
		mTrackClientId = in.readLong();
		mLongitude = in.readDouble();
		mLatitude = in.readDouble();
		mContent = in.readString();
		mCreated = in.readLong();
		
		boolean[] dirtyFlags = new boolean[5];
		in.readBooleanArray(dirtyFlags);
		mTrackClientIdDirty = dirtyFlags[0];
		mLongitudeDirty = dirtyFlags[1];
		mLatitudeDirty = dirtyFlags[2];
		mContentDirty = dirtyFlags[3];
		mCreatedDirty = dirtyFlags[4];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mTrackClientId);
		dest.writeDouble(mLongitude);
		dest.writeDouble(mLatitude);
		dest.writeString(mContent);
		dest.writeLong(mCreated);
		dest.writeBooleanArray(new boolean[] {
			mTrackClientIdDirty,
			mLongitudeDirty,
			mLatitudeDirty,
			mContentDirty,
			mCreatedDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Route.newBuilder();

		if(mTrackClientIdDirty) {
			builder.setTrackClientId(mTrackClientId);
		}
		if(mLongitudeDirty) {
			builder.setLongitude(mLongitude);
		}
		if(mLatitudeDirty) {
			builder.setLatitude(mLatitude);
		}
		if(mContentDirty) {
			builder.setContent(mContent);
		}
		if(mCreatedDirty) {
			builder.setCreated(mCreated);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mTrackClientIdDirty = dirty;
		mLongitudeDirty = dirty;
		mLatitudeDirty = dirty;
		mContentDirty = dirty;
		mCreatedDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setTrackClientId(c.getLong(Indices.TRACK_CLIENT_ID));
		setLongitude(c.getDouble(Indices.LONGITUDE));
		setLatitude(c.getDouble(Indices.LATITUDE));
		setContent(c.getString(Indices.CONTENT));
		setCreated(c.getLong(Indices.CREATED));
	}
	
	public static RouteRecord fromCursor(Cursor c) {
	    RouteRecord item = new RouteRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}

    @SuppressWarnings("deprecation")
	public static RouteRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(RouteRecord.class.getClassLoader());
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
			return bundle.getParcelable(key, RouteRecord.class);
		} else {
			return bundle.getParcelable(key);
		}
	}
	
	public static RouteRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Route.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
