/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.tracks.sqlite.MxInfoDBContract.Trackstage;
import info.mx.tracks.sqlite.MxInfoDBContract.Trackstage.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class TrackstageRecord extends ActiveRecord implements Parcelable {

	private static final ActiveRecordFactory<TrackstageRecord> sFactory = new ActiveRecordFactory<>() {
        @Override
        public TrackstageRecord create(Cursor c) {
            return fromCursor(c);
        }

        @Override
        public String[] getProjection() {
            return PROJECTION;
        }

        @Override
        public Uri getContentUri() {
            return Trackstage.CONTENT_URI;
        }
    };

    			public static ActiveRecordFactory<TrackstageRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<TrackstageRecord> CREATOR 
    	= new Parcelable.Creator<>() {
        public TrackstageRecord createFromParcel(Parcel in) {
            return new TrackstageRecord(in);
        }

        public TrackstageRecord[] newArray(int size) {
            return new TrackstageRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Trackstage._ID,
    	Trackstage.REST_ID,
    	Trackstage.CREATED,
    	Trackstage.COUNTRY,
    	Trackstage.TRACKNAME,
    	Trackstage.LONGITUDE,
    	Trackstage.LATITUDE,
    	Trackstage.INS_LONGITUDE,
    	Trackstage.INS_LATITUDE,
    	Trackstage.INS_DISTANCE,
    	Trackstage.URL,
    	Trackstage.PHONE,
    	Trackstage.NOTES,
    	Trackstage.CONTACT,
    	Trackstage.LICENCE,
    	Trackstage.KIDSTRACK,
    	Trackstage.MEMBERSONLY,
    	Trackstage.OPENMONDAYS,
    	Trackstage.OPENTUESDAYS,
    	Trackstage.OPENWEDNESDAY,
    	Trackstage.OPENTHURSDAY,
    	Trackstage.OPENFRIDAY,
    	Trackstage.OPENSATURDAY,
    	Trackstage.OPENSUNDAY,
    	Trackstage.HOURSMONDAY,
    	Trackstage.HOURSTUESDAY,
    	Trackstage.HOURSWEDNESDAY,
    	Trackstage.HOURSTHURSDAY,
    	Trackstage.HOURSFRIDAY,
    	Trackstage.HOURSSATURDAY,
    	Trackstage.HOURSSUNDAY,
    	Trackstage.RACEONLY,
    	Trackstage.TRACKLENGTH,
    	Trackstage.SOILTYPE,
    	Trackstage.CAMPING,
    	Trackstage.SHOWER,
    	Trackstage.CLEANING,
    	Trackstage.ELECTRICITY,
    	Trackstage.SUPERCROSS,
    	Trackstage.TRACKACCESS,
    	Trackstage.FACEBOOK,
    	Trackstage.FEES,
    	Trackstage.ADRESS,
    	Trackstage.FEESCAMPING,
    	Trackstage.DAYSOPEN,
    	Trackstage.NOISELIMIT,
    	Trackstage.CAMPING_R_VHOOKUPS,
    	Trackstage.SINGLE_TRACK,
    	Trackstage.M_X_TRACK,
    	Trackstage.A4_X4,
    	Trackstage.UTV,
    	Trackstage.QUAD,
    	Trackstage.RATING,
    	Trackstage.TRACKSTATUS,
    	Trackstage.AREATYPE,
    	Trackstage.SCHWIERIGKEIT,
    	Trackstage.ANDROIDID,
    	Trackstage.APPROVED,
    	Trackstage.TRACK_REST_ID,
    	Trackstage.UPDATED,
    	Trackstage.INDOOR,
    	Trackstage.ENDURO
    };
    
    public interface Indices {
    	int _ID = 0;
    	int REST_ID = 1;
    	int CREATED = 2;
    	int COUNTRY = 3;
    	int TRACKNAME = 4;
    	int LONGITUDE = 5;
    	int LATITUDE = 6;
    	int INS_LONGITUDE = 7;
    	int INS_LATITUDE = 8;
    	int INS_DISTANCE = 9;
    	int URL = 10;
    	int PHONE = 11;
    	int NOTES = 12;
    	int CONTACT = 13;
    	int LICENCE = 14;
    	int KIDSTRACK = 15;
    	int MEMBERSONLY = 16;
    	int OPENMONDAYS = 17;
    	int OPENTUESDAYS = 18;
    	int OPENWEDNESDAY = 19;
    	int OPENTHURSDAY = 20;
    	int OPENFRIDAY = 21;
    	int OPENSATURDAY = 22;
    	int OPENSUNDAY = 23;
    	int HOURSMONDAY = 24;
    	int HOURSTUESDAY = 25;
    	int HOURSWEDNESDAY = 26;
    	int HOURSTHURSDAY = 27;
    	int HOURSFRIDAY = 28;
    	int HOURSSATURDAY = 29;
    	int HOURSSUNDAY = 30;
    	int RACEONLY = 31;
    	int TRACKLENGTH = 32;
    	int SOILTYPE = 33;
    	int CAMPING = 34;
    	int SHOWER = 35;
    	int CLEANING = 36;
    	int ELECTRICITY = 37;
    	int SUPERCROSS = 38;
    	int TRACKACCESS = 39;
    	int FACEBOOK = 40;
    	int FEES = 41;
    	int ADRESS = 42;
    	int FEESCAMPING = 43;
    	int DAYSOPEN = 44;
    	int NOISELIMIT = 45;
    	int CAMPING_R_VHOOKUPS = 46;
    	int SINGLE_TRACK = 47;
    	int M_X_TRACK = 48;
    	int A4_X4 = 49;
    	int UTV = 50;
    	int QUAD = 51;
    	int RATING = 52;
    	int TRACKSTATUS = 53;
    	int AREATYPE = 54;
    	int SCHWIERIGKEIT = 55;
    	int ANDROIDID = 56;
    	int APPROVED = 57;
    	int TRACK_REST_ID = 58;
    	int UPDATED = 59;
    	int INDOOR = 60;
    	int ENDURO = 61;
    }
    
    private long mRestId;
    private boolean mRestIdDirty;
    private long mCreated;
    private boolean mCreatedDirty;
    private String mCountry;
    private boolean mCountryDirty;
    private String mTrackname;
    private boolean mTracknameDirty;
    private double mLongitude;
    private boolean mLongitudeDirty;
    private double mLatitude;
    private boolean mLatitudeDirty;
    private double mInsLongitude;
    private boolean mInsLongitudeDirty;
    private double mInsLatitude;
    private boolean mInsLatitudeDirty;
    private long mInsDistance;
    private boolean mInsDistanceDirty;
    private String mUrl;
    private boolean mUrlDirty;
    private String mPhone;
    private boolean mPhoneDirty;
    private String mNotes;
    private boolean mNotesDirty;
    private String mContact;
    private boolean mContactDirty;
    private String mLicence;
    private boolean mLicenceDirty;
    private long mKidstrack;
    private boolean mKidstrackDirty;
    private long mMembersonly;
    private boolean mMembersonlyDirty;
    private long mOpenmondays;
    private boolean mOpenmondaysDirty;
    private long mOpentuesdays;
    private boolean mOpentuesdaysDirty;
    private long mOpenwednesday;
    private boolean mOpenwednesdayDirty;
    private long mOpenthursday;
    private boolean mOpenthursdayDirty;
    private long mOpenfriday;
    private boolean mOpenfridayDirty;
    private long mOpensaturday;
    private boolean mOpensaturdayDirty;
    private long mOpensunday;
    private boolean mOpensundayDirty;
    private String mHoursmonday;
    private boolean mHoursmondayDirty;
    private String mHourstuesday;
    private boolean mHourstuesdayDirty;
    private String mHourswednesday;
    private boolean mHourswednesdayDirty;
    private String mHoursthursday;
    private boolean mHoursthursdayDirty;
    private String mHoursfriday;
    private boolean mHoursfridayDirty;
    private String mHourssaturday;
    private boolean mHourssaturdayDirty;
    private String mHourssunday;
    private boolean mHourssundayDirty;
    private long mRaceonly;
    private boolean mRaceonlyDirty;
    private long mTracklength;
    private boolean mTracklengthDirty;
    private long mSoiltype;
    private boolean mSoiltypeDirty;
    private long mCamping;
    private boolean mCampingDirty;
    private long mShower;
    private boolean mShowerDirty;
    private long mCleaning;
    private boolean mCleaningDirty;
    private long mElectricity;
    private boolean mElectricityDirty;
    private long mSupercross;
    private boolean mSupercrossDirty;
    private String mTrackaccess;
    private boolean mTrackaccessDirty;
    private String mFacebook;
    private boolean mFacebookDirty;
    private String mFees;
    private boolean mFeesDirty;
    private String mAdress;
    private boolean mAdressDirty;
    private String mFeescamping;
    private boolean mFeescampingDirty;
    private String mDaysopen;
    private boolean mDaysopenDirty;
    private String mNoiselimit;
    private boolean mNoiselimitDirty;
    private long mCampingRVhookups;
    private boolean mCampingRVhookupsDirty;
    private long mSingleTrack;
    private boolean mSingleTrackDirty;
    private long mMXTrack;
    private boolean mMXTrackDirty;
    private long mA4X4;
    private boolean mA4X4Dirty;
    private long mUTV;
    private boolean mUTVDirty;
    private long mQuad;
    private boolean mQuadDirty;
    private long mRating;
    private boolean mRatingDirty;
    private String mTrackstatus;
    private boolean mTrackstatusDirty;
    private String mAreatype;
    private boolean mAreatypeDirty;
    private long mSchwierigkeit;
    private boolean mSchwierigkeitDirty;
    private String mAndroidid;
    private boolean mAndroididDirty;
    private long mApproved;
    private boolean mApprovedDirty;
    private long mTrackRestId;
    private boolean mTrackRestIdDirty;
    private long mUpdated;
    private boolean mUpdatedDirty;
    private long mIndoor;
    private boolean mIndoorDirty;
    private long mEnduro;
    private boolean mEnduroDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setRestId(long restId) {
    	mRestId = restId;
    	mRestIdDirty = true;
    }
    
    public long getRestId() {
    	return mRestId;
    }
    
    public void setCreated(long created) {
    	mCreated = created;
    	mCreatedDirty = true;
    }
    
    public long getCreated() {
    	return mCreated;
    }
    
    public void setCountry(String country) {
    	mCountry = country;
    	mCountryDirty = true;
    }
    
    public String getCountry() {
    	return mCountry;
    }
    
    public void setTrackname(String trackname) {
    	mTrackname = trackname;
    	mTracknameDirty = true;
    }
    
    public String getTrackname() {
    	return mTrackname;
    }
    
    public void setLongitude(double longitude) {
    	mLongitude = longitude;
    	mLongitudeDirty = true;
    }
    
    public double getLongitude() {
    	return mLongitude;
    }
    
    public void setLatitude(double latitude) {
    	mLatitude = latitude;
    	mLatitudeDirty = true;
    }
    
    public double getLatitude() {
    	return mLatitude;
    }
    
    public void setInsLongitude(double insLongitude) {
    	mInsLongitude = insLongitude;
    	mInsLongitudeDirty = true;
    }
    
    public double getInsLongitude() {
    	return mInsLongitude;
    }
    
    public void setInsLatitude(double insLatitude) {
    	mInsLatitude = insLatitude;
    	mInsLatitudeDirty = true;
    }
    
    public double getInsLatitude() {
    	return mInsLatitude;
    }
    
    public void setInsDistance(long insDistance) {
    	mInsDistance = insDistance;
    	mInsDistanceDirty = true;
    }
    
    public long getInsDistance() {
    	return mInsDistance;
    }
    
    public void setUrl(String url) {
    	mUrl = url;
    	mUrlDirty = true;
    }
    
    public String getUrl() {
    	return mUrl;
    }
    
    public void setPhone(String phone) {
    	mPhone = phone;
    	mPhoneDirty = true;
    }
    
    public String getPhone() {
    	return mPhone;
    }
    
    public void setNotes(String notes) {
    	mNotes = notes;
    	mNotesDirty = true;
    }
    
    public String getNotes() {
    	return mNotes;
    }
    
    public void setContact(String contact) {
    	mContact = contact;
    	mContactDirty = true;
    }
    
    public String getContact() {
    	return mContact;
    }
    
    public void setLicence(String licence) {
    	mLicence = licence;
    	mLicenceDirty = true;
    }
    
    public String getLicence() {
    	return mLicence;
    }
    
    public void setKidstrack(long kidstrack) {
    	mKidstrack = kidstrack;
    	mKidstrackDirty = true;
    }
    
    public long getKidstrack() {
    	return mKidstrack;
    }
    
    public void setMembersonly(long membersonly) {
    	mMembersonly = membersonly;
    	mMembersonlyDirty = true;
    }
    
    public long getMembersonly() {
    	return mMembersonly;
    }
    
    public void setOpenmondays(long openmondays) {
    	mOpenmondays = openmondays;
    	mOpenmondaysDirty = true;
    }
    
    public long getOpenmondays() {
    	return mOpenmondays;
    }
    
    public void setOpentuesdays(long opentuesdays) {
    	mOpentuesdays = opentuesdays;
    	mOpentuesdaysDirty = true;
    }
    
    public long getOpentuesdays() {
    	return mOpentuesdays;
    }
    
    public void setOpenwednesday(long openwednesday) {
    	mOpenwednesday = openwednesday;
    	mOpenwednesdayDirty = true;
    }
    
    public long getOpenwednesday() {
    	return mOpenwednesday;
    }
    
    public void setOpenthursday(long openthursday) {
    	mOpenthursday = openthursday;
    	mOpenthursdayDirty = true;
    }
    
    public long getOpenthursday() {
    	return mOpenthursday;
    }
    
    public void setOpenfriday(long openfriday) {
    	mOpenfriday = openfriday;
    	mOpenfridayDirty = true;
    }
    
    public long getOpenfriday() {
    	return mOpenfriday;
    }
    
    public void setOpensaturday(long opensaturday) {
    	mOpensaturday = opensaturday;
    	mOpensaturdayDirty = true;
    }
    
    public long getOpensaturday() {
    	return mOpensaturday;
    }
    
    public void setOpensunday(long opensunday) {
    	mOpensunday = opensunday;
    	mOpensundayDirty = true;
    }
    
    public long getOpensunday() {
    	return mOpensunday;
    }
    
    public void setHoursmonday(String hoursmonday) {
    	mHoursmonday = hoursmonday;
    	mHoursmondayDirty = true;
    }
    
    public String getHoursmonday() {
    	return mHoursmonday;
    }
    
    public void setHourstuesday(String hourstuesday) {
    	mHourstuesday = hourstuesday;
    	mHourstuesdayDirty = true;
    }
    
    public String getHourstuesday() {
    	return mHourstuesday;
    }
    
    public void setHourswednesday(String hourswednesday) {
    	mHourswednesday = hourswednesday;
    	mHourswednesdayDirty = true;
    }
    
    public String getHourswednesday() {
    	return mHourswednesday;
    }
    
    public void setHoursthursday(String hoursthursday) {
    	mHoursthursday = hoursthursday;
    	mHoursthursdayDirty = true;
    }
    
    public String getHoursthursday() {
    	return mHoursthursday;
    }
    
    public void setHoursfriday(String hoursfriday) {
    	mHoursfriday = hoursfriday;
    	mHoursfridayDirty = true;
    }
    
    public String getHoursfriday() {
    	return mHoursfriday;
    }
    
    public void setHourssaturday(String hourssaturday) {
    	mHourssaturday = hourssaturday;
    	mHourssaturdayDirty = true;
    }
    
    public String getHourssaturday() {
    	return mHourssaturday;
    }
    
    public void setHourssunday(String hourssunday) {
    	mHourssunday = hourssunday;
    	mHourssundayDirty = true;
    }
    
    public String getHourssunday() {
    	return mHourssunday;
    }
    
    public void setRaceonly(long raceonly) {
    	mRaceonly = raceonly;
    	mRaceonlyDirty = true;
    }
    
    public long getRaceonly() {
    	return mRaceonly;
    }
    
    public void setTracklength(long tracklength) {
    	mTracklength = tracklength;
    	mTracklengthDirty = true;
    }
    
    public long getTracklength() {
    	return mTracklength;
    }
    
    public void setSoiltype(long soiltype) {
    	mSoiltype = soiltype;
    	mSoiltypeDirty = true;
    }
    
    public long getSoiltype() {
    	return mSoiltype;
    }
    
    public void setCamping(long camping) {
    	mCamping = camping;
    	mCampingDirty = true;
    }
    
    public long getCamping() {
    	return mCamping;
    }
    
    public void setShower(long shower) {
    	mShower = shower;
    	mShowerDirty = true;
    }
    
    public long getShower() {
    	return mShower;
    }
    
    public void setCleaning(long cleaning) {
    	mCleaning = cleaning;
    	mCleaningDirty = true;
    }
    
    public long getCleaning() {
    	return mCleaning;
    }
    
    public void setElectricity(long electricity) {
    	mElectricity = electricity;
    	mElectricityDirty = true;
    }
    
    public long getElectricity() {
    	return mElectricity;
    }
    
    public void setSupercross(long supercross) {
    	mSupercross = supercross;
    	mSupercrossDirty = true;
    }
    
    public long getSupercross() {
    	return mSupercross;
    }
    
    public void setTrackaccess(String trackaccess) {
    	mTrackaccess = trackaccess;
    	mTrackaccessDirty = true;
    }
    
    public String getTrackaccess() {
    	return mTrackaccess;
    }
    
    public void setFacebook(String facebook) {
    	mFacebook = facebook;
    	mFacebookDirty = true;
    }
    
    public String getFacebook() {
    	return mFacebook;
    }
    
    public void setFees(String fees) {
    	mFees = fees;
    	mFeesDirty = true;
    }
    
    public String getFees() {
    	return mFees;
    }
    
    public void setAdress(String adress) {
    	mAdress = adress;
    	mAdressDirty = true;
    }
    
    public String getAdress() {
    	return mAdress;
    }
    
    public void setFeescamping(String feescamping) {
    	mFeescamping = feescamping;
    	mFeescampingDirty = true;
    }
    
    public String getFeescamping() {
    	return mFeescamping;
    }
    
    public void setDaysopen(String daysopen) {
    	mDaysopen = daysopen;
    	mDaysopenDirty = true;
    }
    
    public String getDaysopen() {
    	return mDaysopen;
    }
    
    public void setNoiselimit(String noiselimit) {
    	mNoiselimit = noiselimit;
    	mNoiselimitDirty = true;
    }
    
    public String getNoiselimit() {
    	return mNoiselimit;
    }
    
    public void setCampingRVhookups(long campingRVhookups) {
    	mCampingRVhookups = campingRVhookups;
    	mCampingRVhookupsDirty = true;
    }
    
    public long getCampingRVhookups() {
    	return mCampingRVhookups;
    }
    
    public void setSingleTrack(long singleTrack) {
    	mSingleTrack = singleTrack;
    	mSingleTrackDirty = true;
    }
    
    public long getSingleTrack() {
    	return mSingleTrack;
    }
    
    public void setMXTrack(long mXTrack) {
    	mMXTrack = mXTrack;
    	mMXTrackDirty = true;
    }
    
    public long getMXTrack() {
    	return mMXTrack;
    }
    
    public void setA4X4(long a4X4) {
    	mA4X4 = a4X4;
    	mA4X4Dirty = true;
    }
    
    public long getA4X4() {
    	return mA4X4;
    }
    
    public void setUTV(long uTV) {
    	mUTV = uTV;
    	mUTVDirty = true;
    }
    
    public long getUTV() {
    	return mUTV;
    }
    
    public void setQuad(long quad) {
    	mQuad = quad;
    	mQuadDirty = true;
    }
    
    public long getQuad() {
    	return mQuad;
    }
    
    public void setRating(long rating) {
    	mRating = rating;
    	mRatingDirty = true;
    }
    
    public long getRating() {
    	return mRating;
    }
    
    public void setTrackstatus(String trackstatus) {
    	mTrackstatus = trackstatus;
    	mTrackstatusDirty = true;
    }
    
    public String getTrackstatus() {
    	return mTrackstatus;
    }
    
    public void setAreatype(String areatype) {
    	mAreatype = areatype;
    	mAreatypeDirty = true;
    }
    
    public String getAreatype() {
    	return mAreatype;
    }
    
    public void setSchwierigkeit(long schwierigkeit) {
    	mSchwierigkeit = schwierigkeit;
    	mSchwierigkeitDirty = true;
    }
    
    public long getSchwierigkeit() {
    	return mSchwierigkeit;
    }
    
    public void setAndroidid(String androidid) {
    	mAndroidid = androidid;
    	mAndroididDirty = true;
    }
    
    public String getAndroidid() {
    	return mAndroidid;
    }
    
    public void setApproved(long approved) {
    	mApproved = approved;
    	mApprovedDirty = true;
    }
    
    public long getApproved() {
    	return mApproved;
    }
    
    public void setTrackRestId(long trackRestId) {
    	mTrackRestId = trackRestId;
    	mTrackRestIdDirty = true;
    }
    
    public long getTrackRestId() {
    	return mTrackRestId;
    }
    
    public void setUpdated(long updated) {
    	mUpdated = updated;
    	mUpdatedDirty = true;
    }
    
    public long getUpdated() {
    	return mUpdated;
    }
    
    public void setIndoor(long indoor) {
    	mIndoor = indoor;
    	mIndoorDirty = true;
    }
    
    public long getIndoor() {
    	return mIndoor;
    }
    
    public void setEnduro(long enduro) {
    	mEnduro = enduro;
    	mEnduroDirty = true;
    }
    
    public long getEnduro() {
    	return mEnduro;
    }
    
    
    public TrackstageRecord() {
    	super(Trackstage.CONTENT_URI);
	}
	
	private TrackstageRecord(Parcel in) {
    	super(Trackstage.CONTENT_URI);
    	
		setId(in.readLong());
		
		mRestId = in.readLong();
		mCreated = in.readLong();
		mCountry = in.readString();
		mTrackname = in.readString();
		mLongitude = in.readDouble();
		mLatitude = in.readDouble();
		mInsLongitude = in.readDouble();
		mInsLatitude = in.readDouble();
		mInsDistance = in.readLong();
		mUrl = in.readString();
		mPhone = in.readString();
		mNotes = in.readString();
		mContact = in.readString();
		mLicence = in.readString();
		mKidstrack = in.readLong();
		mMembersonly = in.readLong();
		mOpenmondays = in.readLong();
		mOpentuesdays = in.readLong();
		mOpenwednesday = in.readLong();
		mOpenthursday = in.readLong();
		mOpenfriday = in.readLong();
		mOpensaturday = in.readLong();
		mOpensunday = in.readLong();
		mHoursmonday = in.readString();
		mHourstuesday = in.readString();
		mHourswednesday = in.readString();
		mHoursthursday = in.readString();
		mHoursfriday = in.readString();
		mHourssaturday = in.readString();
		mHourssunday = in.readString();
		mRaceonly = in.readLong();
		mTracklength = in.readLong();
		mSoiltype = in.readLong();
		mCamping = in.readLong();
		mShower = in.readLong();
		mCleaning = in.readLong();
		mElectricity = in.readLong();
		mSupercross = in.readLong();
		mTrackaccess = in.readString();
		mFacebook = in.readString();
		mFees = in.readString();
		mAdress = in.readString();
		mFeescamping = in.readString();
		mDaysopen = in.readString();
		mNoiselimit = in.readString();
		mCampingRVhookups = in.readLong();
		mSingleTrack = in.readLong();
		mMXTrack = in.readLong();
		mA4X4 = in.readLong();
		mUTV = in.readLong();
		mQuad = in.readLong();
		mRating = in.readLong();
		mTrackstatus = in.readString();
		mAreatype = in.readString();
		mSchwierigkeit = in.readLong();
		mAndroidid = in.readString();
		mApproved = in.readLong();
		mTrackRestId = in.readLong();
		mUpdated = in.readLong();
		mIndoor = in.readLong();
		mEnduro = in.readLong();
		
		boolean[] dirtyFlags = new boolean[61];
		in.readBooleanArray(dirtyFlags);
		mRestIdDirty = dirtyFlags[0];
		mCreatedDirty = dirtyFlags[1];
		mCountryDirty = dirtyFlags[2];
		mTracknameDirty = dirtyFlags[3];
		mLongitudeDirty = dirtyFlags[4];
		mLatitudeDirty = dirtyFlags[5];
		mInsLongitudeDirty = dirtyFlags[6];
		mInsLatitudeDirty = dirtyFlags[7];
		mInsDistanceDirty = dirtyFlags[8];
		mUrlDirty = dirtyFlags[9];
		mPhoneDirty = dirtyFlags[10];
		mNotesDirty = dirtyFlags[11];
		mContactDirty = dirtyFlags[12];
		mLicenceDirty = dirtyFlags[13];
		mKidstrackDirty = dirtyFlags[14];
		mMembersonlyDirty = dirtyFlags[15];
		mOpenmondaysDirty = dirtyFlags[16];
		mOpentuesdaysDirty = dirtyFlags[17];
		mOpenwednesdayDirty = dirtyFlags[18];
		mOpenthursdayDirty = dirtyFlags[19];
		mOpenfridayDirty = dirtyFlags[20];
		mOpensaturdayDirty = dirtyFlags[21];
		mOpensundayDirty = dirtyFlags[22];
		mHoursmondayDirty = dirtyFlags[23];
		mHourstuesdayDirty = dirtyFlags[24];
		mHourswednesdayDirty = dirtyFlags[25];
		mHoursthursdayDirty = dirtyFlags[26];
		mHoursfridayDirty = dirtyFlags[27];
		mHourssaturdayDirty = dirtyFlags[28];
		mHourssundayDirty = dirtyFlags[29];
		mRaceonlyDirty = dirtyFlags[30];
		mTracklengthDirty = dirtyFlags[31];
		mSoiltypeDirty = dirtyFlags[32];
		mCampingDirty = dirtyFlags[33];
		mShowerDirty = dirtyFlags[34];
		mCleaningDirty = dirtyFlags[35];
		mElectricityDirty = dirtyFlags[36];
		mSupercrossDirty = dirtyFlags[37];
		mTrackaccessDirty = dirtyFlags[38];
		mFacebookDirty = dirtyFlags[39];
		mFeesDirty = dirtyFlags[40];
		mAdressDirty = dirtyFlags[41];
		mFeescampingDirty = dirtyFlags[42];
		mDaysopenDirty = dirtyFlags[43];
		mNoiselimitDirty = dirtyFlags[44];
		mCampingRVhookupsDirty = dirtyFlags[45];
		mSingleTrackDirty = dirtyFlags[46];
		mMXTrackDirty = dirtyFlags[47];
		mA4X4Dirty = dirtyFlags[48];
		mUTVDirty = dirtyFlags[49];
		mQuadDirty = dirtyFlags[50];
		mRatingDirty = dirtyFlags[51];
		mTrackstatusDirty = dirtyFlags[52];
		mAreatypeDirty = dirtyFlags[53];
		mSchwierigkeitDirty = dirtyFlags[54];
		mAndroididDirty = dirtyFlags[55];
		mApprovedDirty = dirtyFlags[56];
		mTrackRestIdDirty = dirtyFlags[57];
		mUpdatedDirty = dirtyFlags[58];
		mIndoorDirty = dirtyFlags[59];
		mEnduroDirty = dirtyFlags[60];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mRestId);
		dest.writeLong(mCreated);
		dest.writeString(mCountry);
		dest.writeString(mTrackname);
		dest.writeDouble(mLongitude);
		dest.writeDouble(mLatitude);
		dest.writeDouble(mInsLongitude);
		dest.writeDouble(mInsLatitude);
		dest.writeLong(mInsDistance);
		dest.writeString(mUrl);
		dest.writeString(mPhone);
		dest.writeString(mNotes);
		dest.writeString(mContact);
		dest.writeString(mLicence);
		dest.writeLong(mKidstrack);
		dest.writeLong(mMembersonly);
		dest.writeLong(mOpenmondays);
		dest.writeLong(mOpentuesdays);
		dest.writeLong(mOpenwednesday);
		dest.writeLong(mOpenthursday);
		dest.writeLong(mOpenfriday);
		dest.writeLong(mOpensaturday);
		dest.writeLong(mOpensunday);
		dest.writeString(mHoursmonday);
		dest.writeString(mHourstuesday);
		dest.writeString(mHourswednesday);
		dest.writeString(mHoursthursday);
		dest.writeString(mHoursfriday);
		dest.writeString(mHourssaturday);
		dest.writeString(mHourssunday);
		dest.writeLong(mRaceonly);
		dest.writeLong(mTracklength);
		dest.writeLong(mSoiltype);
		dest.writeLong(mCamping);
		dest.writeLong(mShower);
		dest.writeLong(mCleaning);
		dest.writeLong(mElectricity);
		dest.writeLong(mSupercross);
		dest.writeString(mTrackaccess);
		dest.writeString(mFacebook);
		dest.writeString(mFees);
		dest.writeString(mAdress);
		dest.writeString(mFeescamping);
		dest.writeString(mDaysopen);
		dest.writeString(mNoiselimit);
		dest.writeLong(mCampingRVhookups);
		dest.writeLong(mSingleTrack);
		dest.writeLong(mMXTrack);
		dest.writeLong(mA4X4);
		dest.writeLong(mUTV);
		dest.writeLong(mQuad);
		dest.writeLong(mRating);
		dest.writeString(mTrackstatus);
		dest.writeString(mAreatype);
		dest.writeLong(mSchwierigkeit);
		dest.writeString(mAndroidid);
		dest.writeLong(mApproved);
		dest.writeLong(mTrackRestId);
		dest.writeLong(mUpdated);
		dest.writeLong(mIndoor);
		dest.writeLong(mEnduro);
		dest.writeBooleanArray(new boolean[] {
			mRestIdDirty,
			mCreatedDirty,
			mCountryDirty,
			mTracknameDirty,
			mLongitudeDirty,
			mLatitudeDirty,
			mInsLongitudeDirty,
			mInsLatitudeDirty,
			mInsDistanceDirty,
			mUrlDirty,
			mPhoneDirty,
			mNotesDirty,
			mContactDirty,
			mLicenceDirty,
			mKidstrackDirty,
			mMembersonlyDirty,
			mOpenmondaysDirty,
			mOpentuesdaysDirty,
			mOpenwednesdayDirty,
			mOpenthursdayDirty,
			mOpenfridayDirty,
			mOpensaturdayDirty,
			mOpensundayDirty,
			mHoursmondayDirty,
			mHourstuesdayDirty,
			mHourswednesdayDirty,
			mHoursthursdayDirty,
			mHoursfridayDirty,
			mHourssaturdayDirty,
			mHourssundayDirty,
			mRaceonlyDirty,
			mTracklengthDirty,
			mSoiltypeDirty,
			mCampingDirty,
			mShowerDirty,
			mCleaningDirty,
			mElectricityDirty,
			mSupercrossDirty,
			mTrackaccessDirty,
			mFacebookDirty,
			mFeesDirty,
			mAdressDirty,
			mFeescampingDirty,
			mDaysopenDirty,
			mNoiselimitDirty,
			mCampingRVhookupsDirty,
			mSingleTrackDirty,
			mMXTrackDirty,
			mA4X4Dirty,
			mUTVDirty,
			mQuadDirty,
			mRatingDirty,
			mTrackstatusDirty,
			mAreatypeDirty,
			mSchwierigkeitDirty,
			mAndroididDirty,
			mApprovedDirty,
			mTrackRestIdDirty,
			mUpdatedDirty,
			mIndoorDirty,
			mEnduroDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Trackstage.newBuilder();

		if(mRestIdDirty) {
			builder.setRestId(mRestId);
		}
		if(mCreatedDirty) {
			builder.setCreated(mCreated);
		}
		if(mCountryDirty) {
			builder.setCountry(mCountry);
		}
		if(mTracknameDirty) {
			builder.setTrackname(mTrackname);
		}
		if(mLongitudeDirty) {
			builder.setLongitude(mLongitude);
		}
		if(mLatitudeDirty) {
			builder.setLatitude(mLatitude);
		}
		if(mInsLongitudeDirty) {
			builder.setInsLongitude(mInsLongitude);
		}
		if(mInsLatitudeDirty) {
			builder.setInsLatitude(mInsLatitude);
		}
		if(mInsDistanceDirty) {
			builder.setInsDistance(mInsDistance);
		}
		if(mUrlDirty) {
			builder.setUrl(mUrl);
		}
		if(mPhoneDirty) {
			builder.setPhone(mPhone);
		}
		if(mNotesDirty) {
			builder.setNotes(mNotes);
		}
		if(mContactDirty) {
			builder.setContact(mContact);
		}
		if(mLicenceDirty) {
			builder.setLicence(mLicence);
		}
		if(mKidstrackDirty) {
			builder.setKidstrack(mKidstrack);
		}
		if(mMembersonlyDirty) {
			builder.setMembersonly(mMembersonly);
		}
		if(mOpenmondaysDirty) {
			builder.setOpenmondays(mOpenmondays);
		}
		if(mOpentuesdaysDirty) {
			builder.setOpentuesdays(mOpentuesdays);
		}
		if(mOpenwednesdayDirty) {
			builder.setOpenwednesday(mOpenwednesday);
		}
		if(mOpenthursdayDirty) {
			builder.setOpenthursday(mOpenthursday);
		}
		if(mOpenfridayDirty) {
			builder.setOpenfriday(mOpenfriday);
		}
		if(mOpensaturdayDirty) {
			builder.setOpensaturday(mOpensaturday);
		}
		if(mOpensundayDirty) {
			builder.setOpensunday(mOpensunday);
		}
		if(mHoursmondayDirty) {
			builder.setHoursmonday(mHoursmonday);
		}
		if(mHourstuesdayDirty) {
			builder.setHourstuesday(mHourstuesday);
		}
		if(mHourswednesdayDirty) {
			builder.setHourswednesday(mHourswednesday);
		}
		if(mHoursthursdayDirty) {
			builder.setHoursthursday(mHoursthursday);
		}
		if(mHoursfridayDirty) {
			builder.setHoursfriday(mHoursfriday);
		}
		if(mHourssaturdayDirty) {
			builder.setHourssaturday(mHourssaturday);
		}
		if(mHourssundayDirty) {
			builder.setHourssunday(mHourssunday);
		}
		if(mRaceonlyDirty) {
			builder.setRaceonly(mRaceonly);
		}
		if(mTracklengthDirty) {
			builder.setTracklength(mTracklength);
		}
		if(mSoiltypeDirty) {
			builder.setSoiltype(mSoiltype);
		}
		if(mCampingDirty) {
			builder.setCamping(mCamping);
		}
		if(mShowerDirty) {
			builder.setShower(mShower);
		}
		if(mCleaningDirty) {
			builder.setCleaning(mCleaning);
		}
		if(mElectricityDirty) {
			builder.setElectricity(mElectricity);
		}
		if(mSupercrossDirty) {
			builder.setSupercross(mSupercross);
		}
		if(mTrackaccessDirty) {
			builder.setTrackaccess(mTrackaccess);
		}
		if(mFacebookDirty) {
			builder.setFacebook(mFacebook);
		}
		if(mFeesDirty) {
			builder.setFees(mFees);
		}
		if(mAdressDirty) {
			builder.setAdress(mAdress);
		}
		if(mFeescampingDirty) {
			builder.setFeescamping(mFeescamping);
		}
		if(mDaysopenDirty) {
			builder.setDaysopen(mDaysopen);
		}
		if(mNoiselimitDirty) {
			builder.setNoiselimit(mNoiselimit);
		}
		if(mCampingRVhookupsDirty) {
			builder.setCampingRVhookups(mCampingRVhookups);
		}
		if(mSingleTrackDirty) {
			builder.setSingleTrack(mSingleTrack);
		}
		if(mMXTrackDirty) {
			builder.setMXTrack(mMXTrack);
		}
		if(mA4X4Dirty) {
			builder.setA4X4(mA4X4);
		}
		if(mUTVDirty) {
			builder.setUTV(mUTV);
		}
		if(mQuadDirty) {
			builder.setQuad(mQuad);
		}
		if(mRatingDirty) {
			builder.setRating(mRating);
		}
		if(mTrackstatusDirty) {
			builder.setTrackstatus(mTrackstatus);
		}
		if(mAreatypeDirty) {
			builder.setAreatype(mAreatype);
		}
		if(mSchwierigkeitDirty) {
			builder.setSchwierigkeit(mSchwierigkeit);
		}
		if(mAndroididDirty) {
			builder.setAndroidid(mAndroidid);
		}
		if(mApprovedDirty) {
			builder.setApproved(mApproved);
		}
		if(mTrackRestIdDirty) {
			builder.setTrackRestId(mTrackRestId);
		}
		if(mUpdatedDirty) {
			builder.setUpdated(mUpdated);
		}
		if(mIndoorDirty) {
			builder.setIndoor(mIndoor);
		}
		if(mEnduroDirty) {
			builder.setEnduro(mEnduro);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mRestIdDirty = dirty;
		mCreatedDirty = dirty;
		mCountryDirty = dirty;
		mTracknameDirty = dirty;
		mLongitudeDirty = dirty;
		mLatitudeDirty = dirty;
		mInsLongitudeDirty = dirty;
		mInsLatitudeDirty = dirty;
		mInsDistanceDirty = dirty;
		mUrlDirty = dirty;
		mPhoneDirty = dirty;
		mNotesDirty = dirty;
		mContactDirty = dirty;
		mLicenceDirty = dirty;
		mKidstrackDirty = dirty;
		mMembersonlyDirty = dirty;
		mOpenmondaysDirty = dirty;
		mOpentuesdaysDirty = dirty;
		mOpenwednesdayDirty = dirty;
		mOpenthursdayDirty = dirty;
		mOpenfridayDirty = dirty;
		mOpensaturdayDirty = dirty;
		mOpensundayDirty = dirty;
		mHoursmondayDirty = dirty;
		mHourstuesdayDirty = dirty;
		mHourswednesdayDirty = dirty;
		mHoursthursdayDirty = dirty;
		mHoursfridayDirty = dirty;
		mHourssaturdayDirty = dirty;
		mHourssundayDirty = dirty;
		mRaceonlyDirty = dirty;
		mTracklengthDirty = dirty;
		mSoiltypeDirty = dirty;
		mCampingDirty = dirty;
		mShowerDirty = dirty;
		mCleaningDirty = dirty;
		mElectricityDirty = dirty;
		mSupercrossDirty = dirty;
		mTrackaccessDirty = dirty;
		mFacebookDirty = dirty;
		mFeesDirty = dirty;
		mAdressDirty = dirty;
		mFeescampingDirty = dirty;
		mDaysopenDirty = dirty;
		mNoiselimitDirty = dirty;
		mCampingRVhookupsDirty = dirty;
		mSingleTrackDirty = dirty;
		mMXTrackDirty = dirty;
		mA4X4Dirty = dirty;
		mUTVDirty = dirty;
		mQuadDirty = dirty;
		mRatingDirty = dirty;
		mTrackstatusDirty = dirty;
		mAreatypeDirty = dirty;
		mSchwierigkeitDirty = dirty;
		mAndroididDirty = dirty;
		mApprovedDirty = dirty;
		mTrackRestIdDirty = dirty;
		mUpdatedDirty = dirty;
		mIndoorDirty = dirty;
		mEnduroDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setRestId(c.getLong(Indices.REST_ID));
		setCreated(c.getLong(Indices.CREATED));
		setCountry(c.getString(Indices.COUNTRY));
		setTrackname(c.getString(Indices.TRACKNAME));
		setLongitude(c.getDouble(Indices.LONGITUDE));
		setLatitude(c.getDouble(Indices.LATITUDE));
		setInsLongitude(c.getDouble(Indices.INS_LONGITUDE));
		setInsLatitude(c.getDouble(Indices.INS_LATITUDE));
		setInsDistance(c.getLong(Indices.INS_DISTANCE));
		setUrl(c.getString(Indices.URL));
		setPhone(c.getString(Indices.PHONE));
		setNotes(c.getString(Indices.NOTES));
		setContact(c.getString(Indices.CONTACT));
		setLicence(c.getString(Indices.LICENCE));
		setKidstrack(c.getLong(Indices.KIDSTRACK));
		setMembersonly(c.getLong(Indices.MEMBERSONLY));
		setOpenmondays(c.getLong(Indices.OPENMONDAYS));
		setOpentuesdays(c.getLong(Indices.OPENTUESDAYS));
		setOpenwednesday(c.getLong(Indices.OPENWEDNESDAY));
		setOpenthursday(c.getLong(Indices.OPENTHURSDAY));
		setOpenfriday(c.getLong(Indices.OPENFRIDAY));
		setOpensaturday(c.getLong(Indices.OPENSATURDAY));
		setOpensunday(c.getLong(Indices.OPENSUNDAY));
		setHoursmonday(c.getString(Indices.HOURSMONDAY));
		setHourstuesday(c.getString(Indices.HOURSTUESDAY));
		setHourswednesday(c.getString(Indices.HOURSWEDNESDAY));
		setHoursthursday(c.getString(Indices.HOURSTHURSDAY));
		setHoursfriday(c.getString(Indices.HOURSFRIDAY));
		setHourssaturday(c.getString(Indices.HOURSSATURDAY));
		setHourssunday(c.getString(Indices.HOURSSUNDAY));
		setRaceonly(c.getLong(Indices.RACEONLY));
		setTracklength(c.getLong(Indices.TRACKLENGTH));
		setSoiltype(c.getLong(Indices.SOILTYPE));
		setCamping(c.getLong(Indices.CAMPING));
		setShower(c.getLong(Indices.SHOWER));
		setCleaning(c.getLong(Indices.CLEANING));
		setElectricity(c.getLong(Indices.ELECTRICITY));
		setSupercross(c.getLong(Indices.SUPERCROSS));
		setTrackaccess(c.getString(Indices.TRACKACCESS));
		setFacebook(c.getString(Indices.FACEBOOK));
		setFees(c.getString(Indices.FEES));
		setAdress(c.getString(Indices.ADRESS));
		setFeescamping(c.getString(Indices.FEESCAMPING));
		setDaysopen(c.getString(Indices.DAYSOPEN));
		setNoiselimit(c.getString(Indices.NOISELIMIT));
		setCampingRVhookups(c.getLong(Indices.CAMPING_R_VHOOKUPS));
		setSingleTrack(c.getLong(Indices.SINGLE_TRACK));
		setMXTrack(c.getLong(Indices.M_X_TRACK));
		setA4X4(c.getLong(Indices.A4_X4));
		setUTV(c.getLong(Indices.UTV));
		setQuad(c.getLong(Indices.QUAD));
		setRating(c.getLong(Indices.RATING));
		setTrackstatus(c.getString(Indices.TRACKSTATUS));
		setAreatype(c.getString(Indices.AREATYPE));
		setSchwierigkeit(c.getLong(Indices.SCHWIERIGKEIT));
		setAndroidid(c.getString(Indices.ANDROIDID));
		setApproved(c.getLong(Indices.APPROVED));
		setTrackRestId(c.getLong(Indices.TRACK_REST_ID));
		setUpdated(c.getLong(Indices.UPDATED));
		setIndoor(c.getLong(Indices.INDOOR));
		setEnduro(c.getLong(Indices.ENDURO));
	}
	
	public static TrackstageRecord fromCursor(Cursor c) {
	    TrackstageRecord item = new TrackstageRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}

    @SuppressWarnings("deprecation")
   	public static TrackstageRecord fromBundle(Bundle bundle, String key) {
        bundle.setClassLoader(TrackstageRecord.class.getClassLoader());
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
            return bundle.getParcelable(key, TrackstageRecord.class);
        } else {
            return bundle.getParcelable(key);
        }
	}
	
	public static TrackstageRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Trackstage.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
