/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;

import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxAdminDBMigrationV6 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"alter table pictures add column LocalFile text "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
