/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;

import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxAdminDBMigrationV3 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table trackstageBrother ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"trackRestId integer, " +
			"created integer default ( strftime ( '%s' , 'now' ) ), " +
			"Trackname text, " +
			"Longitude real, " +
			"Latitude real, " +
			"Country text default \"\", " +
			"androidid text, " +
			"urlDetailXml text, " +
			"contentDetailXml text default '', " +
			"urlPhoto text, " +
			"contentPhoto text default '' " +
			") "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
