/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;

import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxCalMigrationV1 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table DownLoadSite ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"display text, " +
			"url text, " +
			"createdate integer default ( strftime ( '%s' , 'now' ) ), " +
			"quellfile_id integer " +
			") "
		);	
		db.execSQL(
			"create table MXSerie ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"webId integer, " +
			"created_at integer, " +
			"updated_at integer, " +
			"name text, " +
			"series_url text, " +
			"year integer, " +
			"quellfile_id integer " +
			") "
		);	
		db.execSQL(
			"create table MxSeriesTrack ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"webId integer, " +
			"web_series_id integer, " +
			"web_track_id integer, " +
			"created_at integer, " +
			"updated_at integer, " +
			"event_date integer, " +
			"notes text, " +
			"quellfile_id integer " +
			") "
		);	
		db.execSQL(
			"create table MxTrack ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"webId integer, " +
			"created_at integer, " +
			"updated_at integer, " +
			"address text, " +
			"city text, " +
			"email text, " +
			"name text, " +
			"phone text, " +
			"state_code text, " +
			"website text, " +
			"zip integer, " +
			"quellfile_id integer, " +
			"lat real, " +
			"lng real " +
			") "
		);	
		db.execSQL(
			"create table QuellFile ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"downloadSite_id integer, " +
			"createdate integer default ( strftime ( '%s' , 'now' ) ), " +
			"updatedCount integer, " +
			"content text default \"\", " +
			"log text default \"\", " +
			"url text " +
			") "
		);	
		db.execSQL(
			"create table importstatusCal( " +
			"_id integer primary key autoincrement, " +
			"msg text, " +
			"created integer default 0 " +
			") "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
