/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;

import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxAdminDBMigrationV1 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"create table trackstageRid ( " +
			"_id integer primary key autoincrement, " +
			"restId integer, " +
			"created integer default ( strftime ( '%s' , 'now' ) ), " +
			"urlMapPointsJson text, " +
			"urlDetailXml text, " +
			"contentMapPointsJson text, " +
			"contentDetailXml text " +
			") "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
