/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops.mxcal;

import android.content.Intent;
import android.os.Bundle;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;

public abstract class AbstractOpRiderPlanetLoadOperation extends Operation {
	public static final String ACTION_OP_RIDER_PLANET_LOAD = "info.hannes.mechadmin.ops.mxcal.MxCalService.actions.OP_RIDER_PLANET_LOAD";

	public static final String EXTRA_URL = "info.hannes.mechadmin.ops.mxcal.MxCalService.extras.URL";
	public static final String EXTRA_DOWN_LOAD_ID = "info.hannes.mechadmin.ops.mxcal.MxCalService.extras.DOWN_LOAD_ID";
	public static final String EXTRA_ONLY_EXTRACT = "info.hannes.mechadmin.ops.mxcal.MxCalService.extras.ONLY_EXTRACT";

	static class Args {
		public String url;
		public long downLoadId;
		public boolean onlyExtract;
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpRiderPlanetLoadOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractOpRiderPlanetLoadOperation.ACTION_OP_RIDER_PLANET_LOAD, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent(String url, long downLoadId, boolean onlyExtract) {
		Intent intent = new Intent(ACTION_OP_RIDER_PLANET_LOAD);
		intent.setClass(Mechanoid.getApplicationContext(), MxCalService.class);
		
		Bundle extras = new Bundle();
		extras.putString(EXTRA_URL, url);
		extras.putLong(EXTRA_DOWN_LOAD_ID, downLoadId);
		extras.putBoolean(EXTRA_ONLY_EXTRACT, onlyExtract);
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		Bundle extras = context.getIntent().getExtras();
		args.url = extras.getString(EXTRA_URL);
		args.downLoadId = extras.getLong(EXTRA_DOWN_LOAD_ID);
		args.onlyExtract = extras.getBoolean(EXTRA_ONLY_EXTRACT);
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
