/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops.mxcal;

import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

public abstract class AbstractMxCalServiceConfiguration extends OperationServiceConfiguration {
	private OperationConfigurationRegistry mOperationConfigurationRegistry = new MxCalServiceOperationConfigurationRegistry();
	
	@Override
	public OperationConfigurationRegistry getOperationConfigurationRegistry() {
		return mOperationConfigurationRegistry;
	}
}
