/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops.mxcal;

import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;

public abstract class AbstractMxCalService extends OperationService {
	
	public static final OperationServiceConfiguration CONFIG = new MxCalServiceConfiguration();
	
	@Override
	protected OperationProcessor createProcessor() {
		return new MxCalProcessor(this);
	}
	
	public AbstractMxCalService(boolean enableLogging) {
		super(enableLogging);
	}
}
