/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops.mxcal;

public class MxCalService extends AbstractMxCalService {
    public MxCalService() {
        super(false);
    }
}
