/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops.mxcal;

public class MxCalServiceOperationConfigurationRegistry extends AbstractMxCalServiceOperationConfigurationRegistry {

}

