/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops.mxcal;

import android.content.Intent;
import android.os.Bundle;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;

public abstract class AbstractOpMxCallPush2ServerOperation extends Operation {
	public static final String ACTION_OP_MX_CALL_PUSH2_SERVER = "info.hannes.mechadmin.ops.mxcal.MxCalService.actions.OP_MX_CALL_PUSH2_SERVER";

	public static final String EXTRA_BASIC = "info.hannes.mechadmin.ops.mxcal.MxCalService.extras.BASIC";

	static class Args {
		public String basic;
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpMxCallPush2ServerOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractOpMxCallPush2ServerOperation.ACTION_OP_MX_CALL_PUSH2_SERVER, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent(String basic) {
		Intent intent = new Intent(ACTION_OP_MX_CALL_PUSH2_SERVER);
		intent.setClass(Mechanoid.getApplicationContext(), MxCalService.class);
		
		Bundle extras = new Bundle();
		extras.putString(EXTRA_BASIC, basic);
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		Bundle extras = context.getIntent().getExtras();
		args.basic = extras.getString(EXTRA_BASIC);
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
