/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops.mxcal;

import android.content.Intent;
import android.os.Bundle;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;

public abstract class AbstractOpLoadPictureVideoOperation extends Operation {
	public static final String ACTION_OP_LOAD_PICTURE_VIDEO = "info.hannes.mechadmin.ops.mxcal.MxCalService.actions.OP_LOAD_PICTURE_VIDEO";


	static class Args {
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpLoadPictureVideoOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractOpLoadPictureVideoOperation.ACTION_OP_LOAD_PICTURE_VIDEO, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent() {
		Intent intent = new Intent(ACTION_OP_LOAD_PICTURE_VIDEO);
		intent.setClass(Mechanoid.getApplicationContext(), MxCalService.class);
		
		Bundle extras = new Bundle();
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
