/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops.mxcal;

import com.robotoworks.mechanoid.ops.OperationConfiguration;
import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;

import java.util.HashMap;

public abstract class AbstractMxCalServiceOperationConfigurationRegistry extends OperationConfigurationRegistry {

	private HashMap<String, OperationConfiguration> mOperationConfigurations;

	public AbstractMxCalServiceOperationConfigurationRegistry() {

		mOperationConfigurations = new HashMap<String, OperationConfiguration>();

		registerOperationConfigurations();
	}

	protected void registerOperationConfigurations(){
		registerOperationConfiguration(OpLoadPictureVideoOperation.ACTION_OP_LOAD_PICTURE_VIDEO, new OpLoadPictureVideoOperation.Configuration());
		registerOperationConfiguration(OpTracksMapLoadOperation.ACTION_OP_TRACKS_MAP_LOAD, new OpTracksMapLoadOperation.Configuration());
		registerOperationConfiguration(OpRiderPlanetLoadOperation.ACTION_OP_RIDER_PLANET_LOAD, new OpRiderPlanetLoadOperation.Configuration());
		registerOperationConfiguration(OpBrothersLoadOperation.ACTION_OP_BROTHERS_LOAD, new OpBrothersLoadOperation.Configuration());
		registerOperationConfiguration(OpBrothersPushOperation.ACTION_OP_BROTHERS_PUSH, new OpBrothersPushOperation.Configuration());
		registerOperationConfiguration(OpMxCalLoadSearchOperation.ACTION_OP_MX_CAL_LOAD_SEARCH, new OpMxCalLoadSearchOperation.Configuration());
		registerOperationConfiguration(OpMxCallPush2ServerOperation.ACTION_OP_MX_CALL_PUSH2_SERVER, new OpMxCallPush2ServerOperation.Configuration());
		registerOperationConfiguration(OpMxCallFixLatLngOperation.ACTION_OP_MX_CALL_FIX_LAT_LNG, new OpMxCallFixLatLngOperation.Configuration());
	}

	protected void registerOperationConfiguration(String action, OperationConfiguration config) {
		mOperationConfigurations.put(action, config);
	}

	@Override
	public OperationConfiguration getOperationConfiguration(String action) {
		return mOperationConfigurations.get(action);
	}
}
