/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops.google;

import com.robotoworks.mechanoid.ops.OperationServiceConfiguration;
import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;

public abstract class AbstractMxGoogleServiceConfiguration extends OperationServiceConfiguration {
	private OperationConfigurationRegistry mOperationConfigurationRegistry = new MxGoogleServiceOperationConfigurationRegistry();
	
	@Override
	public OperationConfigurationRegistry getOperationConfigurationRegistry() {
		return mOperationConfigurationRegistry;
	}
}
