/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops.google;

import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationProcessor;			

public abstract class AbstractMxGoogleProcessor extends OperationProcessor {

	@Override
	protected Operation createOperation(String action) {
		return MxGoogleService.CONFIG
			.getOperationConfigurationRegistry()
			.getOperationConfiguration(action)
			.createOperation();
	}
	
	public AbstractMxGoogleProcessor(OperationService service, boolean enableLogging) {
		super(service, enableLogging);
	}
}
