/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.tracks.ops.google;

import java.util.HashMap;

import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;
import com.robotoworks.mechanoid.ops.OperationConfiguration;

public abstract class AbstractMxGoogleServiceOperationConfigurationRegistry extends OperationConfigurationRegistry {
	
	private HashMap<String, OperationConfiguration> mOperationConfigurations;
	
	public AbstractMxGoogleServiceOperationConfigurationRegistry() {
		
		mOperationConfigurations = new HashMap<String, OperationConfiguration>();
		
		registerOperationConfigurations();
	}
	
	protected void registerOperationConfigurations(){
		registerOperationConfiguration(OpGetRouteOperation.ACTION_OP_GET_ROUTE, new OpGetRouteOperation.Configuration());
	}
	
	protected void registerOperationConfiguration(String action, OperationConfiguration config) {
		mOperationConfigurations.put(action, config);
	}

	@Override
	public OperationConfiguration getOperationConfiguration(String action) {
		return mOperationConfigurations.get(action);
	}
}
