/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.sqlite.migrations;

import android.database.sqlite.SQLiteDatabase;

import com.robotoworks.mechanoid.db.SQLiteMigration;

public class DefaultMxInfoDBMigrationV11 extends SQLiteMigration {
	@Override
	public void onBeforeUp(SQLiteDatabase db) {}
	
	@Override
	public void up(SQLiteDatabase db) {
		db.execSQL(
			"drop table message "
		);	
	}
	
	@Override
	public void onAfterUp(SQLiteDatabase db) {}
}
