/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.ops;

import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationService;
import com.robotoworks.mechanoid.ops.OperationProcessor;

import info.mx.core.ops.MxInfoService;

public abstract class AbstractMxInfoProcessor extends OperationProcessor {

	@Override
	protected Operation createOperation(String action) {
		return MxInfoService.CONFIG
			.getOperationConfigurationRegistry()
			.getOperationConfiguration(action)
			.createOperation();
	}
	
	public AbstractMxInfoProcessor(OperationService service, boolean enableLogging) {
		super(service, enableLogging);
	}
}
