/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.ops;

import com.robotoworks.mechanoid.ops.OperationConfiguration;
import com.robotoworks.mechanoid.ops.OperationConfigurationRegistry;

import java.util.HashMap;

import info.mx.core.ops.OpDownLoadImageOperation;
import info.mx.core.ops.OpGetLatLngOperation;
import info.mx.core.ops.OpGetWeatherOperation;
import info.mx.core.ops.OpPostImagesOperation;
import info.mx.core.ops.OpPostTrackAppovedOperation;
import info.mx.core.ops.OpPushSharedImageOperation;
import info.mx.core.ops.OpRecalcDistanceOperation;
import info.mx.core.ops.OpResetLocalImagesOperation;
import info.mx.core.ops.OpWeatherCachedOperation;
import info.mx.tracks.ops.OpSyncFromServerOperation;

public abstract class AbstractMxInfoServiceOperationConfigurationRegistry extends OperationConfigurationRegistry {

    private final HashMap<String, OperationConfiguration> mOperationConfigurations;

    public AbstractMxInfoServiceOperationConfigurationRegistry() {

        mOperationConfigurations = new HashMap<>();

        registerOperationConfigurations();
    }

    protected void registerOperationConfigurations() {
        registerOperationConfiguration(OpRecalcDistanceOperation.ACTION_OP_RECALC_DISTANCE, new OpRecalcDistanceOperation.Configuration());
        registerOperationConfiguration(OpSyncFromServerOperation.ACTION_OP_SYNC_FROM_SERVER, new OpSyncFromServerOperation.Configuration());
        registerOperationConfiguration(OpPostTrackAppovedOperation.ACTION_OP_POST_TRACK_APPOVED, new OpPostTrackAppovedOperation.Configuration());
        registerOperationConfiguration(OpPostImagesOperation.ACTION_OP_POST_IMAGES, new OpPostImagesOperation.Configuration());
        registerOperationConfiguration(OpResetLocalImagesOperation.ACTION_OP_RESET_LOCAL_IMAGES, new OpResetLocalImagesOperation.Configuration());
        registerOperationConfiguration(OpPushSharedImageOperation.ACTION_OP_PUSH_SHARED_IMAGE, new OpPushSharedImageOperation.Configuration());
        registerOperationConfiguration(OpDownLoadImageOperation.ACTION_OP_DOWN_LOAD_IMAGE, new OpDownLoadImageOperation.Configuration());
        registerOperationConfiguration(OpGetLatLngOperation.ACTION_OP_GET_LAT_LNG, new OpGetLatLngOperation.Configuration());
        registerOperationConfiguration(OpGetWeatherOperation.ACTION_OP_GET_WEATHER, new OpGetWeatherOperation.Configuration());
        registerOperationConfiguration(OpWeatherCachedOperation.ACTION_OP_GET_WEATHER_CACHED, new OpWeatherCachedOperation.Configuration());
    }

    protected void registerOperationConfiguration(String action, OperationConfiguration config) {
        mOperationConfigurations.put(action, config);
    }

    @Override
    public OperationConfiguration getOperationConfiguration(String action) {
        return mOperationConfigurations.get(action);
    }
}
