/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.ops;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import android.content.Intent;
import android.os.Bundle;

import info.mx.core.ops.MxInfoService;
import info.mx.core.ops.OpResetLocalImagesOperation;

public abstract class AbstractOpResetLocalImagesOperation extends Operation {
	public static final String ACTION_OP_RESET_LOCAL_IMAGES = "info.mx.tracks.ops.MxInfoService.actions.OP_RESET_LOCAL_IMAGES";


	public static class Args {
	}

    public static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpResetLocalImagesOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {

            return bridge.findPendingRequestByActionWithExtras(AbstractOpResetLocalImagesOperation.ACTION_OP_RESET_LOCAL_IMAGES, intent.getExtras());
			
		}
	}
	
	public static Intent newIntent() {
		Intent intent = new Intent(ACTION_OP_RESET_LOCAL_IMAGES);
		intent.setClass(Mechanoid.getApplicationContext(), MxInfoService.class);
		
		Bundle extras = new Bundle();
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
