/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.core_generated.sqlite.MxInfoDBContract.Events2series;
import info.mx.core_generated.sqlite.MxInfoDBContract.Events2series.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class Events2seriesRecord extends ActiveRecord implements Parcelable {

	private static final ActiveRecordFactory<Events2seriesRecord> sFactory = new ActiveRecordFactory<>() {
        @Override
        public Events2seriesRecord create(Cursor c) {
            return fromCursor(c);
        }

        @Override
        public String[] getProjection() {
            return PROJECTION;
        }

        @Override
        public Uri getContentUri() {
            return Events2series.CONTENT_URI;
        }
    };

    			public static ActiveRecordFactory<Events2seriesRecord> getFactory() {
		return sFactory;
	}

    public static final Parcelable.Creator<Events2seriesRecord> CREATOR
    	= new Parcelable.Creator<>() {
        public Events2seriesRecord createFromParcel(Parcel in) {
            return new Events2seriesRecord(in);
        }

        public Events2seriesRecord[] newArray(int size) {
            return new Events2seriesRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Events2series._ID,
    	Events2series.TRACK_REST_ID,
    	Events2series.SERIES_REST_ID,
    	Events2series.COMMENT,
    	Events2series.APPROVED,
    	Events2series.EVENT_DATE,
    	Events2series.SERIESNAME
    };
    
    public interface Indices {
    	int _ID = 0;
    	int TRACK_REST_ID = 1;
    	int SERIES_REST_ID = 2;
    	int COMMENT = 3;
    	int APPROVED = 4;
    	int EVENT_DATE = 5;
    	int SERIESNAME = 6;
    }
    
    private long mTrackRestId;
    private boolean mTrackRestIdDirty;
    private long mSeriesRestId;
    private boolean mSeriesRestIdDirty;
    private String mComment;
    private boolean mCommentDirty;
    private long mApproved;
    private boolean mApprovedDirty;
    private long mEventDate;
    private boolean mEventDateDirty;
    private String mSeriesname;
    private boolean mSeriesnameDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setTrackRestId(long trackRestId) {
    	mTrackRestId = trackRestId;
    	mTrackRestIdDirty = true;
    }
    
    public long getTrackRestId() {
    	return mTrackRestId;
    }
    public void setSeriesRestId(long seriesRestId) {
    	mSeriesRestId = seriesRestId;
    	mSeriesRestIdDirty = true;
    }
    
    public long getSeriesRestId() {
    	return mSeriesRestId;
    }
    public void setComment(String comment) {
    	mComment = comment;
    	mCommentDirty = true;
    }
    
    public String getComment() {
    	return mComment;
    }
    public void setApproved(long approved) {
    	mApproved = approved;
    	mApprovedDirty = true;
    }
    
    public long getApproved() {
    	return mApproved;
    }
    public void setEventDate(long eventDate) {
    	mEventDate = eventDate;
    	mEventDateDirty = true;
    }
    
    public long getEventDate() {
    	return mEventDate;
    }
    public void setSeriesname(String seriesname) {
    	mSeriesname = seriesname;
    	mSeriesnameDirty = true;
    }
    
    public String getSeriesname() {
    	return mSeriesname;
    }
    
    public Events2seriesRecord() {
    	super(Events2series.CONTENT_URI);
	}
	
	private Events2seriesRecord(Parcel in) {
    	super(Events2series.CONTENT_URI);
    	
		setId(in.readLong());
		
		mTrackRestId = in.readLong();
		mSeriesRestId = in.readLong();
		mComment = in.readString();
		mApproved = in.readLong();
		mEventDate = in.readLong();
		mSeriesname = in.readString();
		
		boolean[] dirtyFlags = new boolean[6];
		in.readBooleanArray(dirtyFlags);
		mTrackRestIdDirty = dirtyFlags[0];
		mSeriesRestIdDirty = dirtyFlags[1];
		mCommentDirty = dirtyFlags[2];
		mApprovedDirty = dirtyFlags[3];
		mEventDateDirty = dirtyFlags[4];
		mSeriesnameDirty = dirtyFlags[5];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mTrackRestId);
		dest.writeLong(mSeriesRestId);
		dest.writeString(mComment);
		dest.writeLong(mApproved);
		dest.writeLong(mEventDate);
		dest.writeString(mSeriesname);
		dest.writeBooleanArray(new boolean[] {
			mTrackRestIdDirty,
			mSeriesRestIdDirty,
			mCommentDirty,
			mApprovedDirty,
			mEventDateDirty,
			mSeriesnameDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Events2series.newBuilder();

		if(mTrackRestIdDirty) {
			builder.setTrackRestId(mTrackRestId);
		}
		if(mSeriesRestIdDirty) {
			builder.setSeriesRestId(mSeriesRestId);
		}
		if(mCommentDirty) {
			builder.setComment(mComment);
		}
		if(mApprovedDirty) {
			builder.setApproved(mApproved);
		}
		if(mEventDateDirty) {
			builder.setEventDate(mEventDate);
		}
		if(mSeriesnameDirty) {
			builder.setSeriesname(mSeriesname);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mTrackRestIdDirty = dirty;
		mSeriesRestIdDirty = dirty;
		mCommentDirty = dirty;
		mApprovedDirty = dirty;
		mEventDateDirty = dirty;
		mSeriesnameDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setTrackRestId(c.getLong(Indices.TRACK_REST_ID));
		setSeriesRestId(c.getLong(Indices.SERIES_REST_ID));
		setComment(c.getString(Indices.COMMENT));
		setApproved(c.getLong(Indices.APPROVED));
		setEventDate(c.getLong(Indices.EVENT_DATE));
		setSeriesname(c.getString(Indices.SERIESNAME));
	}
	
	public static Events2seriesRecord fromCursor(Cursor c) {
	    Events2seriesRecord item = new Events2seriesRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}

    @SuppressWarnings("deprecation")
	public static Events2seriesRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(Events2seriesRecord.class.getClassLoader());
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
			return bundle.getParcelable(key, Events2seriesRecord.class);
		} else {
			return bundle.getParcelable(key);
		}
	}
	
	public static Events2seriesRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Events2series.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
