/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops;

import com.robotoworks.mechanoid.ops.OperationService;

public class StageingProcessor extends AbstractStageingProcessor {
    public StageingProcessor(OperationService service) {
        super(service, false);
    }
}
