/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadminGen.ops;

public class StageingService extends AbstractStageingService {
    public StageingService() {
        super(false);
    }
}
