/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops;

import android.content.Intent;
import android.os.Bundle;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationConfiguration;
import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.OperationServiceBridge;

public abstract class AbstractOpPostPictureApprovedOperation extends Operation {
	public static final String ACTION_OP_POST_PICTURE_APPROVED = "info.hannes.mechadmin.ops.StageingService.actions.OP_POST_PICTURE_APPROVED";

	public static final String EXTRA_PICTURE_REST_ID = "info.hannes.mechadmin.ops.StageingService.extras.PICTURE_REST_ID";
	public static final String EXTRA_STATUS = "info.hannes.mechadmin.ops.StageingService.extras.STATUS";

	static class Args {
		public long pictureRestId;
		public int status;
	}
	
	static class Configuration extends OperationConfiguration {
		@Override 
		public Operation createOperation() {
			return new OpPostPictureApprovedOperation();
		}
		
		@Override
		public Intent findMatchOnConstraint(OperationServiceBridge bridge, Intent intent) {
			Intent existingRequest = bridge.findPendingRequestByActionWithExtras(AbstractOpPostPictureApprovedOperation.ACTION_OP_POST_PICTURE_APPROVED, intent.getExtras());
			
			return existingRequest;
			
		}
	}
	
	public static final Intent newIntent(long pictureRestId, int status) {
		Intent intent = new Intent(ACTION_OP_POST_PICTURE_APPROVED);
		intent.setClass(Mechanoid.getApplicationContext(), StageingService.class);
		
		Bundle extras = new Bundle();
		extras.putLong(EXTRA_PICTURE_REST_ID, pictureRestId);
		extras.putInt(EXTRA_STATUS, status);
		
		intent.putExtras(extras);
		
		return intent;
		
	}

	@Override
	public OperationResult execute(OperationContext context) {
		Args args = new Args();
		
		Bundle extras = context.getIntent().getExtras();
		args.pictureRestId = extras.getLong(EXTRA_PICTURE_REST_ID);
		args.status = extras.getInt(EXTRA_STATUS);
		
		return onExecute(context, args);
	}
			
	protected abstract OperationResult onExecute(OperationContext context, Args args);
}
