/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops;

import android.content.Intent;
import android.os.Bundle;

import com.robotoworks.mechanoid.ops.OperationContext;
import com.robotoworks.mechanoid.ops.OperationResult;
import com.robotoworks.mechanoid.ops.Ops;

import info.mx.tracks.ops.OpSyncFromServerOperation;

public class OpStageSplitOperation extends AbstractOpStageSplitOperation {
    @Override
    protected OperationResult onExecute(OperationContext context, Args args) {

        try {
            StageAdminHelper.doStagesSplitToAcceptableAskable();

            final Intent intentM = OpSyncFromServerOperation.newIntent(true, args.flavor);
            Ops.execute(intentM);
            final Bundle bundle = new Bundle();
            return OperationResult.ok(bundle);
        } catch (final Exception e) {
            return OperationResult.error(e);
        }

    }
}
