/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.net.Uri;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;

import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.util.Closeables;

import info.hannes.mechadmin_gen.sqlite.MxAdminDBContract.Videos;
import info.hannes.mechadmin_gen.sqlite.MxAdminDBContract.Videos.Builder;

public class VideosRecord extends ActiveRecord implements Parcelable {

	private static ActiveRecordFactory<VideosRecord> sFactory = new ActiveRecordFactory<VideosRecord>() {
		@Override
		public VideosRecord create(Cursor c) {
			return fromCursor(c);
		}

		@Override
		public Uri getContentUri() {
			return Videos.CONTENT_URI;
		}
		
		@Override
		public String[] getProjection() {
			return PROJECTION;
		}
	};
	
	public static ActiveRecordFactory<VideosRecord> getFactory() {
		return sFactory;
	}

    public static final Creator<VideosRecord> CREATOR
    	= new Creator<VideosRecord>() {
        public VideosRecord createFromParcel(Parcel in) {
            return new VideosRecord(in);
        }

        public VideosRecord[] newArray(int size) {
            return new VideosRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Videos._ID,
    	Videos.REST_ID,
    	Videos.TRACK_ID,
    	Videos.CHANGED,
    	Videos.WWW,
    	Videos.TRACK_REST_ID,
    	Videos.LOCAL_FILE
    };
    
    public interface Indices {
    	int _ID = 0;
    	int REST_ID = 1;
    	int TRACK_ID = 2;
    	int CHANGED = 3;
    	int WWW = 4;
    	int TRACK_REST_ID = 5;
    	int LOCAL_FILE = 6;
    }
    
    private long mRestId;
    private boolean mRestIdDirty;
    private long mTrackId;
    private boolean mTrackIdDirty;
    private long mChanged;
    private boolean mChangedDirty;
    private String mWww;
    private boolean mWwwDirty;
    private long mTrackRestId;
    private boolean mTrackRestIdDirty;
    private String mLocalFile;
    private boolean mLocalFileDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setRestId(long restId) {
    	mRestId = restId;
    	mRestIdDirty = true;
    }
    
    public long getRestId() {
    	return mRestId;
    }
    
    public void setTrackId(long trackId) {
    	mTrackId = trackId;
    	mTrackIdDirty = true;
    }
    
    public long getTrackId() {
    	return mTrackId;
    }
    
    public void setChanged(long changed) {
    	mChanged = changed;
    	mChangedDirty = true;
    }
    
    public long getChanged() {
    	return mChanged;
    }
    
    public void setWww(String www) {
    	mWww = www;
    	mWwwDirty = true;
    }
    
    public String getWww() {
    	return mWww;
    }
    
    public void setTrackRestId(long trackRestId) {
    	mTrackRestId = trackRestId;
    	mTrackRestIdDirty = true;
    }
    
    public long getTrackRestId() {
    	return mTrackRestId;
    }
    
    public void setLocalFile(String localFile) {
    	mLocalFile = localFile;
    	mLocalFileDirty = true;
    }
    
    public String getLocalFile() {
    	return mLocalFile;
    }
    
    
    public VideosRecord() {
    	super(Videos.CONTENT_URI);
	}
	
	private VideosRecord(Parcel in) {
    	super(Videos.CONTENT_URI);
    	
		setId(in.readLong());
		
		mRestId = in.readLong();
		mTrackId = in.readLong();
		mChanged = in.readLong();
		mWww = in.readString();
		mTrackRestId = in.readLong();
		mLocalFile = in.readString();
		
		boolean[] dirtyFlags = new boolean[6];
		in.readBooleanArray(dirtyFlags);
		mRestIdDirty = dirtyFlags[0];
		mTrackIdDirty = dirtyFlags[1];
		mChangedDirty = dirtyFlags[2];
		mWwwDirty = dirtyFlags[3];
		mTrackRestIdDirty = dirtyFlags[4];
		mLocalFileDirty = dirtyFlags[5];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mRestId);
		dest.writeLong(mTrackId);
		dest.writeLong(mChanged);
		dest.writeString(mWww);
		dest.writeLong(mTrackRestId);
		dest.writeString(mLocalFile);
		dest.writeBooleanArray(new boolean[] {
			mRestIdDirty,
			mTrackIdDirty,
			mChangedDirty,
			mWwwDirty,
			mTrackRestIdDirty,
			mLocalFileDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Videos.newBuilder();

		if(mRestIdDirty) {
			builder.setRestId(mRestId);
		}
		if(mTrackIdDirty) {
			builder.setTrackId(mTrackId);
		}
		if(mChangedDirty) {
			builder.setChanged(mChanged);
		}
		if(mWwwDirty) {
			builder.setWww(mWww);
		}
		if(mTrackRestIdDirty) {
			builder.setTrackRestId(mTrackRestId);
		}
		if(mLocalFileDirty) {
			builder.setLocalFile(mLocalFile);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mRestIdDirty = dirty;
		mTrackIdDirty = dirty;
		mChangedDirty = dirty;
		mWwwDirty = dirty;
		mTrackRestIdDirty = dirty;
		mLocalFileDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setRestId(c.getLong(Indices.REST_ID));
		setTrackId(c.getLong(Indices.TRACK_ID));
		setChanged(c.getLong(Indices.CHANGED));
		setWww(c.getString(Indices.WWW));
		setTrackRestId(c.getLong(Indices.TRACK_REST_ID));
		setLocalFile(c.getString(Indices.LOCAL_FILE));
	}
	
	public static VideosRecord fromCursor(Cursor c) {
	    VideosRecord item = new VideosRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}
	
	public static VideosRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(VideosRecord.class.getClassLoader());
		return bundle.getParcelable(key);
	}
	
	public static VideosRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Videos.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
