/*
 * Generated by Robotoworks Mechanoid
 */
package info.hannes.mechadmin_gen.ops.mxcal;

import com.robotoworks.mechanoid.ops.Operation;
import com.robotoworks.mechanoid.ops.OperationProcessor;
import com.robotoworks.mechanoid.ops.OperationService;

public abstract class AbstractMxCalProcessor extends OperationProcessor {

	@Override
	protected Operation createOperation(String action) {
		return MxCalService.CONFIG
			.getOperationConfigurationRegistry()
			.getOperationConfiguration(action)
			.createOperation();
	}
	
	public AbstractMxCalProcessor(OperationService service, boolean enableLogging) {
		super(service, enableLogging);
	}
}
