/*
 * Generated by Robotoworks Mechanoid
 */
package info.mx.core_generated.sqlite;

import android.content.ContentResolver;
import android.database.Cursor;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import android.net.Uri;
import info.mx.core_generated.sqlite.MxInfoDBContract.Eventsum;
import info.mx.core_generated.sqlite.MxInfoDBContract.Eventsum.Builder;
import com.robotoworks.mechanoid.util.Closeables;
import com.robotoworks.mechanoid.db.ActiveRecord;
import com.robotoworks.mechanoid.db.ActiveRecordFactory;
import com.robotoworks.mechanoid.Mechanoid;
import com.robotoworks.mechanoid.db.AbstractValuesBuilder;

public class EventsumRecord extends ActiveRecord implements Parcelable {

	private static final ActiveRecordFactory<EventsumRecord> sFactory = new ActiveRecordFactory<>() {
        @Override
        public EventsumRecord create(Cursor c) {
            return fromCursor(c);
        }

        @Override
        public String[] getProjection() {
            return PROJECTION;
        }

        @Override
        public Uri getContentUri() {
            return Eventsum.CONTENT_URI;
        }
    };

    			public static ActiveRecordFactory<EventsumRecord> getFactory() {
		return sFactory;
	}

    public static final Creator<EventsumRecord> CREATOR
    	= new Creator<>() {
        public EventsumRecord createFromParcel(Parcel in) {
            return new EventsumRecord(in);
        }

        public EventsumRecord[] newArray(int size) {
            return new EventsumRecord[size];
        }
    };
    
    public static String[] PROJECTION = {
    	Eventsum._ID,
    	Eventsum.TRACK_REST_ID,
    	Eventsum.EVENTCOUNT
    };
    
    public interface Indices {
    	int _ID = 0;
    	int TRACK_REST_ID = 1;
    	int EVENTCOUNT = 2;
    }
    
    private long mTrackRestId;
    private boolean mTrackRestIdDirty;
    private long mEventcount;
    private boolean mEventcountDirty;
    
    @Override
    protected String[] _getProjection() {
    	return PROJECTION;
    }
    
    public void setTrackRestId(long trackRestId) {
    	mTrackRestId = trackRestId;
    	mTrackRestIdDirty = true;
    }
    
    public long getTrackRestId() {
    	return mTrackRestId;
    }
    public void setEventcount(long eventcount) {
    	mEventcount = eventcount;
    	mEventcountDirty = true;
    }
    
    public long getEventcount() {
    	return mEventcount;
    }
    
    public EventsumRecord() {
    	super(Eventsum.CONTENT_URI);
	}
	
	private EventsumRecord(Parcel in) {
    	super(Eventsum.CONTENT_URI);
    	
		setId(in.readLong());
		
		mTrackRestId = in.readLong();
		mEventcount = in.readLong();
		
		boolean[] dirtyFlags = new boolean[2];
		in.readBooleanArray(dirtyFlags);
		mTrackRestIdDirty = dirtyFlags[0];
		mEventcountDirty = dirtyFlags[1];
	}
	
	@Override
	public int describeContents() {
	    return 0;
	}
	
	@Override
	public void writeToParcel(Parcel dest, int flags) {
		dest.writeLong(getId());
		dest.writeLong(mTrackRestId);
		dest.writeLong(mEventcount);
		dest.writeBooleanArray(new boolean[] {
			mTrackRestIdDirty,
			mEventcountDirty
		});
	}
	
	@Override
	protected AbstractValuesBuilder createBuilder() {
		Builder builder = Eventsum.newBuilder();

		if(mTrackRestIdDirty) {
			builder.setTrackRestId(mTrackRestId);
		}
		if(mEventcountDirty) {
			builder.setEventcount(mEventcount);
		}
		
		return builder;
	}
	
    @Override
	public void makeDirty(boolean dirty){
		mTrackRestIdDirty = dirty;
		mEventcountDirty = dirty;
	}

	@Override
	protected void setPropertiesFromCursor(Cursor c) {
		setId(c.getLong(Indices._ID));
		setTrackRestId(c.getLong(Indices.TRACK_REST_ID));
		setEventcount(c.getLong(Indices.EVENTCOUNT));
	}
	
	public static EventsumRecord fromCursor(Cursor c) {
	    EventsumRecord item = new EventsumRecord();
	    
		item.setPropertiesFromCursor(c);
		
		item.makeDirty(false);
		
	    return item;
	}

    @SuppressWarnings("deprecation")
	public static EventsumRecord fromBundle(Bundle bundle, String key) {
		bundle.setClassLoader(EventsumRecord.class.getClassLoader());
		if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.TIRAMISU) {
			return bundle.getParcelable(key, EventsumRecord.class);
		} else {
			return bundle.getParcelable(key);
		}
	}
	
	public static EventsumRecord get(long id) {
	    Cursor c = null;
	    
	    ContentResolver resolver = Mechanoid.getContentResolver();
	    
	    try {
	        c = resolver.query(Eventsum.CONTENT_URI.buildUpon()
			.appendPath(String.valueOf(id)).build(), PROJECTION, null, null, null);
	        
	        if(!c.moveToFirst()) {
	            return null;
	        }
	        
	        return fromCursor(c);
	    } finally {
	        Closeables.closeSilently(c);
	    }
	}
}
