name: pull request

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  env-job:
    runs-on: ubuntu-latest
    outputs:
      modified-branch-name: ${{ steps.env.outputs.MODIFIED_BRANCH_NAME }}
    name: Modify branch name
    steps:
      - name: Sets MODIFIED_BRANCH_NAME
        id: env
        env:
          name: "${{env.BRANCH_NAME}}"
        run: |
          echo "MODIFIED_BRANCH_NAME=${name//\//-}" >> ${GITHUB_OUTPUT}
          cat ${GITHUB_OUTPUT}

  BuildFlavors:
    name: Build All and test JDK
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 17 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew assembleDebug
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      #      - name: Run tests
      #        run: ./gradlew test
      - name: cleanup
        run: ./signing/cleanup.sh
  TestPro:
    name: Test Pro JDK ${{ matrix.java_version }} ${{ matrix.api }} ${{ matrix.tag }} ${{ matrix.abi }}
    runs-on: macOS-latest
    needs:
      - env-job
    strategy:
      fail-fast: false
      matrix:
        java_version: [ 17 ]
        api: [ 28 ]
        abi: [ x86_64 ]
        tag: [ 'default' ]
    #        include:
    #          #          - api: 31
    #          #            abi: x86_64
    #          #            tag: 'google_apis'
    #          - api: 30
    #            abi: x86_64
    #            tag: 'google_apis'
    #            java_version: 17
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0
      - name: show envs
        run: |
          echo ${{ needs.env-job.outputs.modified-branch-name }}
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java_version }}
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Decrypt keystore
        run: ./signing/decrypt.sh
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Build project
        run: ./gradlew :MXApp:assemblePaidDebug
        env:
          CRYPT_PASS: ${{ secrets.CRYPT_PASS }}
      - name: Run instrumentation tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.1.4
        with:
          cmd: |
            ./gradlew :MXApp:connectedPaidDebugAndroidTest --continue
          api: ${{ matrix.api }}
          tag: ${{ matrix.tag }}
          abi: ${{ matrix.abi }}
          cmdOptions: -noaudio -no-boot-anim -no-window
          bootTimeout: 840 # seconds = 12 minutes
      - name: Archive screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: MXPro-Screenshots-${{ needs.env-job.outputs.modified-branch-name }}
          path: |
            MXApp/build/outputs/connected_android_test_additional_output/paidDebugAndroidTest/connected
      - name: Archive Espresso results
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: MXPro-Espresso-${{ needs.env-job.outputs.modified-branch-name }}
          path: |
            MXApp/build/outputs/androidTest-results/connected
      - name: cleanup
        run: ./signing/cleanup.sh
  Check:
    name: Check
    runs-on: ubuntu-latest
    needs:
      - env-job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: show envs
        run: |
          echo ${{ needs.env-job.outputs.modified-branch-name }}
      - uses: gradle/wrapper-validation-action@v1
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v3.6.0
        with:
          distribution: 'adopt'
          java-version: 17
      - name: gradle check
        run: ./gradlew lintDebug # ktlintCheck
      - name: Archive Lint report
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        with:
          name: MX-Lint-report-${{ needs.env-job.outputs.modified-branch-name }}
          path: ./**/build/reports/lint-results*.html
